### ISSUE TITLE
smooth_l1 loss

### ISSUE THREAD

**Issue by YongshengDong** [xuannianz/EfficientDet#100]
Hi, 
Is it '-1' for "ignore" anchors on this line for smooth l1 loss?

https://github.com/xuannianz/EfficientDet/blob/fb7c244ad5ff03959c169dbd3d23ea924a48a161/losses.py#L99

**Comment by xuannianz** [comment]
No, @YongshengDong . It's to find positive anchors and only positive ones would be calculated in smooth l1.

**Comment by YongshengDong** [comment]
@xuannianz Thank you~
