### ISSUE TITLE
Multiple keypoints

### ISSUE THREAD

**Issue by bhack** [xuannianz/EfficientDet#101]
Can you expand over quadrangle with an arbitrary number of keypoints classes? So you can train on face landmarks, human pose and any other points of interest inside an object quad.

**Comment by xuannianz** [comment]
Hi @bhack ,sounds interesting. But currently I have no time for that.

**Comment by bhack** [comment]
Also if It Is in Pytorch take a look at https://github.com/tensorboy/centerpose/

**Comment by bhack** [comment]
@xuannianz An interesting bottom-up head could be KPNet https://arxiv.org/pdf/2003.07543.pdf
