### ISSUE TITLE
ValueError: Tensor stem_bn_trainable:0 in true_fn is accessed from false_fn.

### ISSUE THREAD

**Issue by IsaacPatole** [xuannianz/EfficientDet#102]
What could be the cause of this issue? I just cloned the repo and using python inference.py

**Comment by km23630** [comment]
I need more information.

Do you use the Windows development environment?
In my case it works fine. (Ubuntu 18.04)

**Comment by IsaacPatole** [comment]
Yes, using windows 10 currently

**Comment by km23630** [comment]
> Yes, using windows 10 currently

when I run this code on window, This code did not work properly.
try ubuntu

**Comment by xuannianz** [comment]
Hi @IsaacPatole , this project does not support tf > 2.0 currectly.

**Comment by IsaacPatole** [comment]
@km23630 thanks but is that a OS problem? @xuannianz  which OS did you use? also I will try downgrading my tensorflow and will test again.

**Comment by xuannianz** [comment]
@IsaacPatole ubuntu 18.04. The problem may be due to tf version. There a huge gap between tf 1.x and tf 2.x. If you're using tf 2.0 (not tf 2.1), you can replace the customize BatchNormalization layer with the builtin one. But you may encounter other problems even though you fix this one.

**Comment by IsaacPatole** [comment]
@xuannianz @km23630 the error is gone, you can close this thread, moved to tf 1.14, getting another error now, 
ValueError: Layer #495 (named "class_head"), weight <tf.Variable 'pyramid_classification/kernel:0' shape=(3, 3, 88, 180) dtype=float32> has shape (3, 3, 88, 180), but the saved weight has shape (720, 88, 3, 3)   
 ..... while trying to use weights from this link : https://onedrive.live.com/?authkey=%21ABynatZTEy539B8&cid=04887CD42DB77448&id=4887CD42DB77448%211986496&parId=4887CD42DB77448%21723893&o=OneUp

Means that h5 file is not compatible with the model architecture, you also didnt provide the h5 file, do I have train the model on my own first?

**Comment by km23630** [comment]
s that h5 file is not compatible with the model architecture, you also didnt provide the h5 file, do I have train the model on my own first?

check your 'phi' parameter

**Comment by IsaacPatole** [comment]
it is 1 in inference.py ? what it should be?

**Comment by IsaacPatole** [comment]
@km23630 I tried changing it in the range of 0-6 (as in model.py file ie: assert phi in range(7) in line 222 ) but nothing works ! 

ValueError: Layer #495 (named "class_head"), weight <tf.Variable 'pyramid_classification/kernel:0' shape=(3, 3, 88, 180) dtype=float32> has shape (3, 3, 88, 180), but the saved weight has shape (720, 88, 3, 3)

seems like the shape is flipped somehow...

**Comment by xuannianz** [comment]
Hi @IsaacPatole  , the weights you load were trained on coco which has 80 classes, so you should specify coco `classes` and `num_classes` in inference.py which are of VOC now.

**Comment by IsaacPatole** [comment]
`def main():
    os.environ['CUDA_VISIBLE_DEVICES'] = '0'
    
    phi = 0
    weighted_bifpn = False
    model_path = r'checkpoints/coco_50_1.5735_1.5532.h5'
    image_sizes = (512, 640, 768, 896, 1024, 1280, 1408)
    image_size = image_sizes[phi]
    #classes = ['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'diningtable',
    #           'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor']
    classes = ['person','bicycle', 'car','motorcycle','airplane','bus','train','truck','boat','traffic light','fire hydrant','stop sign','parking meter','bench','bird','cat','dog','horse','sheep','cow','elephant','bear','zebra','giraffe','backpack','umbrella','handbag','tie','suitcase','frisbee','skis','snowboard','sports ball','kite','baseball bat','baseball glove','skateboard','surfboard','tennis racket','bottle','wine glass', 'cup','fork', 'knife','spoon','bowl','banana','apple','sandwich','orange','broccoli','carrot','hot dog','pizza','donut','cake','chair','couch','potted plant','bed', 'dining table','toilet','tv','laptop','mouse','remote','keyboard','cell phone','microwave','oven','toaster','sink','refrigerator','book', 'clock','vase','scissors','teddy bear','hair drier','toothbrush']
    num_classes = len(classes)
    score_threshold = 0.5
    colors = [np.random.randint(0, 256, 3).tolist() for _ in range(num_classes)]
    model, prediction_model = efficientdet(phi=phi,
                                           weighted_bifpn=weighted_bifpn,
                                           num_classes=num_classes,
                                           score_threshold=score_threshold)
    prediction_model.load_weights(model_path, by_name=True)`

**Comment by IsaacPatole** [comment]
@xuannianz getting the same error 
ValueError: Layer #329 (named "BiFPN_0_P6_conv"), weight <tf.Variable 'BiFPN_0_P6_conv/kernel:0' shape=(3, 3, 320, 64) dtype=float32> has shape (3, 3, 320, 64), but the saved weight has shape (88, 320, 3, 3)

**Comment by IsaacPatole** [comment]
@km23630 using your trained weights here I guess, what changes you have made in the inference.py to get it work?

**Comment by IsaacPatole** [comment]
@km23630 which tensorflow version did you use?

**Comment by IsaacPatole** [comment]
Hey, @km23630  @xuannianz  any suggestions on it?

**Comment by xuannianz** [comment]
@IsaacPatole , set `phi=1`.

**Comment by IsaacPatole** [comment]
@xuannianz It worked ! thank you so much ! I modified assuming its an image size which would resize my image to 640*640 , why other parameters didnt work here?

**Comment by km23630** [comment]
![https://s3-us-west-2.amazonaws.com/secure.notion-static.com/be2675cd-e682-499f-bbee-196de21fc38f/Untitled.png](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/be2675cd-e682-499f-bbee-196de21fc38f/Untitled.png)
![image](https://user-images.githubusercontent.com/30399899/76809615-c15b6c80-682e-11ea-9b64-fe8377c1a329.png)

yes.
In this code, Input size is fixed

**Comment by IsaacPatole** [comment]
Cool! thank you so much @xuannianz
