### ISSUE TITLE
Convert trained model .h5 to TFLite

### ISSUE THREAD

**Issue by geekzain** [xuannianz/EfficientDet#103]
Hey there, I am trying to convert the .h5 to tflite for Edge TPU compatibility but I am stuck with this error which doesn't allow me to load the model for conversion:

TypeError: ('Keyword argument not understood:', 'freeze')

In my knowledge this error occurs because this implementation uses a batch norm layer that is identical to that of Keras but with one extra Boolean parameter called freeze that controls the freezing.  Keras then return an error back saying that it doesn't know the argument. Is there an other way to do this. This is what I am trying to do:

```
model= tf.keras.models.load_model('/path/to/.h5')
tflite_converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = tflite_converter.convert()
open("tf_lite_model.tflite", "wb").write(tflite_model) 
```

Also I am not even sure batch norm is compatible with Edge TPU's. If that's not the case I would need to unfold this layer or merge it to a convolution layer. Thanks in advance !

**Comment by 2696120622** [comment]
@geekzain 
I am also trying to convert trained model .h5 to tflite. I fixed your issue by passing the custom_objects in tf.lite.TFLiteConverter.from_keras_model. However, I got another runtimeerror about some unresolved ops in tflite in inference when calling interpreter.allocate_tensor().
What I did as follows.
`
from tensorflow import keras  
import tensorflow as tf  
import layers as layers_new  
import initializers  
import losses  
import efficientnet  

custom_objects = {
'BatchNormalization': layers_new.BatchNormalization,
'swish' : efficientnet.get_swish(backend=keras.backend,layers=keras.layers,models=keras.models,utils=keras.utils),
'FixedDropout' : efficientnet.get_dropout(backend=keras.backend,layers=keras.layers,models=keras.models,utils=keras.utils),
'wBiFPNAdd' : layers_new.wBiFPNAdd,
'PriorProbability' : initializers.PriorProbability,
'RegressBoxes' : layers_new.RegressBoxes,
'FilterDetections' : layers_new.FilterDetections,
'ClipBoxes' : layers_new.ClipBoxes,
'_smooth_l1' : losses.smooth_l1(),
'_focal' : losses.focal(),
}  
input_shapes = {'input_2':[None,768,768,3],'input_5':[None,184140,4]}  
tf.enable_control_flow_v2()  
converter = tf.lite.TFLiteConverter.from_keras_model_file('E:/object_detection/EfficientDet-region_anchor_opt_mbconv-head-ckpts/inference_ckpts/ckpts_B0_image-size-768/mbconv-se-head_1e-5_unfreeze-backbone_freeze-bn/csv_04_0.6736_0.7484.h5',
custom_objects=custom_objects,
input_shapes=input_shapes,
)  
converter.allow_custom_ops=True  
tflite_model = converter.convert()  
open("E:/object_detection/EfficientDet-region_anchor_opt_mbconv-head-ckpts/tflites/ckpts_B0_image-size-768/mbconv-se-head_1e-5_unfreeze-backbone_freeze-bn/csv_04_0.6736_0.7484.tflite", "wb").write(tflite_model)  
interpreter = tf.lite.Interpreter(model_path="E:/object_detection/EfficientDet-region_anchor_opt_mbconv-head-ckpts/tflites/ckpts_B0_image-size-768/mbconv-se-head_1e-5_unfreeze-backbone_freeze-bn/csv_04_0.6736_0.7484.tflite")  
interpreter.allocate_tensors()`  

> https://github.com/tensorflow/tensorflow/issues/28485#issuecomment-574453673

If you have made any progress, can you share there?

**Comment by bhack** [comment]
@geekzain The Ideal for EdgeTPU would be to have the new lite backbones. See https://blog.tensorflow.org/2020/03/higher-accuracy-on-vision-models-with-efficientnet-lite.html?m=1

**Comment by geekzain** [comment]
@bhack Oh that's awesome ! I am glad to see more and more upcoming support for edge computing. Do you have any idea if this is already implemented for object detection?

**Comment by bhack** [comment]
@geekzain You can track https://github.com/google/automl/issues/11
