### ISSUE TITLE
Official release

### ISSUE THREAD

**Issue by bhack** [xuannianz/EfficientDet#104]
If you are interested there is an official Google release now https://twitter.com/tanmingxing/status/1239959559969488897

**Comment by km23630** [comment]
@bhack wow thanks!

**Comment by xuannianz** [comment]
@bhack , thanks. I have already spent three days synchronizing with it.

**Comment by bhack** [comment]
See also https://github.com/tensorflow/tpu/issues/611#issuecomment-600232019

**Comment by bhack** [comment]
I suppose that we could have a Efficient-net lite backbone soon https://github.com/tensorflow/models/issues/6996#issuecomment-600129431
