### ISSUE TITLE
Broken csv mode. (in model.py after sync w/ official)

### ISSUE THREAD

**Issue by KnightHawk15** [xuannianz/EfficientDet#106]
Worked last night, with the new update I'm getting the following error. Any suggestions for troubleshooting? Thanks :)
**Input:**
`!python3 train.py --snapshot imagenet --phi 3 --gpu 0  --random-transform --compute-val-loss --freeze-backbone --batch-size 8 --steps 1000 --snapshot-path /content/drive/My\ Drive/EfficientDetFoods/snapshots csv /EfficientDet/openfood/train.csv /EfficientDet/openfood/class_map.csv --val-annotations-path /EfficientDet/openfood/val.csv`

**Error:**
*`Traceback (most recent call last):
  File "train.py", line 377, in <module>
    main()
  File "train.py", line 314, in main
    detect_quadrangle=args.detect_quadrangle
  File "/EfficientDet/model.py", line 437, in efficientdet
    classification = [class_net([feature, i]) for i, feature in enumerate(fpn_features)]
  File "/EfficientDet/model.py", line 437, in <listcomp>
    classification = [class_net([feature, i]) for i, feature in enumerate(fpn_features)]
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/keras/engine/base_layer.py", line 898, in __call__
    outputs = self.call(cast_inputs, *args, **kwargs)`*

*`  File "/EfficientDet/model.py", line 405, in call
    feature = self.bns[i][level](feature)`*

*`  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/training/tracking/data_structures.py", line 357, in __getitem__
    return self._storage[key]
TypeError: list indices must be integers or slices, not Tensor`*

**Comment by xuannianz** [comment]
Hi @KnightHawk15 , thanks. You can switch to tf 2.x or pull the latest code.

**Comment by KnightHawk15** [comment]
> Hi @KnightHawk15 , thanks. You can switch to tf 2.x or pull the latest code.

Awwwesome! thank a load!
