### ISSUE TITLE
Model inference does not work well with the changed code.

### ISSUE THREAD

**Issue by km23630** [xuannianz/EfficientDet#108]
![image](https://user-images.githubusercontent.com/30399899/77271833-05e57d00-6cf3-11ea-83b9-20bd0cd931ea.png)

I used efficientdet-d1.h5 model.
In the changed code, the values of boxes, scores, and labels become [-1, ..., -1].
How can I solve this problem?

**Comment by xuannianz** [comment]
@km23630 , you may use the old one, the weights link has been updated.

**Comment by km23630** [comment]
@xuannianz 
I used the latest code(commit 54) and weight(efficient-d1.h5).
The problem is not solved.
Why is that?

**Comment by km23630** [comment]
I tried several model_weight (coco D0, D1 and pascalVoc weight)
All [-1, ..., -1] create arrays.
I want to know how to solve the problem.

**Comment by xuannianz** [comment]
@km23630 ,did you modify anything? How about downloading the code at another place and testing?

**Comment by km23630** [comment]
> @km23630 ,did you modify anything? How about downloading the code at another place and testing?

![image](https://user-images.githubusercontent.com/30399899/77544767-d601c980-6eec-11ea-81e3-cfdfd39a0ab1.png)

I used this weight to inference and match all package versions.
The old (before sync) code still works fine.
It could be an environmental issue, so I tried it in a new environment, but the results were the same.

**Comment by km23630** [comment]
let me know your dev environment plz

**Comment by xuannianz** [comment]
I am using tf 2.1 now, but I have tested under tf 1.15, it works well.

**Comment by km23630** [comment]
thanks! 
The problem was solved after complying with all requirement.txt on the new development environment!
