### ISSUE TITLE
Inference  time

### ISSUE THREAD

**Issue by Jilliansea** [xuannianz/EfficientDet#110]
Inference  time is too big?
model | det  time| inference time

D2 | 0.075 | 0.17
D3 | 0.10s | 0.20

**Comment by xuannianz** [comment]
Hi @Jilliansea , did you use cpu? How long should it be normally?

**Comment by Jilliansea** [comment]
I use GPU. I have test nas-fpn based on mmdetection, all inference time=0.15s,  which is smaller than D3, but  as it said in efficientdet paper, D4 should be more efficient than nas-fpn; Have you  test the official code? I counter trouble in test pure inference  time in official code( it doesn't have inference code for multi-image to test inference  time)

**Comment by Jilliansea** [comment]
> Hi @Jilliansea , did you use cpu? How long should it be normally?

I use GPU. I have test nas-fpn based on mmdetection, all inference time=0.15s, which is smaller than D3, but as it said in efficientdet paper, D4 should be more efficient than nas-fpn; Have you test the official code? I counter trouble in test pure inference time in official code( it doesn't have inference code for multi-image to test inference time)
