### ISSUE TITLE
Evaluate Custom CSV dataset

### ISSUE THREAD

**Issue by dhiaul98** [xuannianz/EfficientDet#119]
How to evaluate custom CSV dataset?
 i got this
ValueError: Layer #338 (named "class_head"), weight <tf.Variable 'pyramid_classification/kernel:0' shape=(3, 3, 64, 180) dtype=float32> has shape (3, 3, 64, 180), but the saved weight has shape (171, 64, 3, 3).
when trying using pascal

**Comment by GaurangGavai** [comment]
I think you need to set the phi value in inference.py to the correct value that you trained with.

**Comment by xuannianz** [comment]
Hi @dhiaul98 , do you specify `--detect-quadrangle` during training? If so, you need to set detect_quadrangle=True when build model.

**Comment by dhiaul98** [comment]
No, i'am not using --detect-quadrangle before, and I think I have set phi with the correct value

**Comment by dhiaul98** [comment]
Oke , i'am sorry the problem in this case is human error in my code, thank you all
