### ISSUE TITLE
can you provide the pretrain model?

### ISSUE THREAD

**Issue by HaiLongEmb** [xuannianz/EfficientDet#12]
can you provide the pretrain model? @xuannianz

**Comment by xuannianz** [comment]
Hi @HaiLongEmb, I uploaded two trained weights on PASCAL VOC just now and will train on COCO in the next few days.

**Comment by abhigoku10** [comment]
@xuannianz how much time did it take up to train the model on Pascal voc and what is the system specification

**Comment by xuannianz** [comment]
HI @abhigoku10, it takes a dozen hours to train EfficientNetB0 on a single 2080Ti.

**Comment by AnjalyE** [comment]
Hi @xuannianz ,
I could not find the pretrained weights on PASCAL VOC in the repository. Could you please let me know where I can find them?

**Comment by bobo41092003** [comment]
hi  @xuannianz  ,

I use PASCAL VOC phi=1 weights for evaluation, but the evaluation results are all 0 mAP, What do you think? ? Thank you.

![123](https://user-images.githubusercontent.com/57713823/98619882-152b4080-233f-11eb-8eca-caa0e85a32fd.JPG)
