### ISSUE TITLE
Quadrangle detection no longer working properly

### ISSUE THREAD

**Issue by SpiderBraids** [xuannianz/EfficientDet#120]
I am currently trying to use EfficientDet's support for quadrangle detection. However, I have not been able to get it to work properly. When I try to train my data (which I have checked that it has been properly formatted), I receive an error saying:
 
> ValueError: slice index 8 of dimension 2 out of bounds. for 'strided_slice_2' (op: 'StridedSlice') with input shapes: [?,?,4], [2], [2], [2] and with computed input tensors: input[1] = <0 8>, input[2] = <0 9>, input[3] = <1 1>.

I have found that a few changes to BoxNet class allow the training to proceed without errors. However, I then run into more errors when trying to use the trained model to perform quadrangle detection, and I have not managed to find a way to make detection work.

**Comment by xuannianz** [comment]
For quadrangle detection, you'd better use the code before Mar.21. I'm busying with other stuff and have not tested the latest code.
