### ISSUE TITLE
 Does the source code support running in tensorflow = <1.12 with card gtx1080

### ISSUE THREAD

**Issue by phucnhs** [xuannianz/EfficientDet#122]
Thanks !

**Comment by xuannianz** [comment]
Maybe no, I only test under tf 1.15 and tf 2.1.

**Comment by km23630** [comment]
When I tested it, it didn't work properly in version 1.14.
but 1.15 and 2.1 work well

**Comment by phucnhs** [comment]
thanks you , i will close issues

**Comment by moothes** [comment]
I have started to train this model on TF 1.12 after some modifications to the source code. With 16 batch size, I got around 11.5 mAP on COCO at 11 epoch. I am continuing the training process now.

**Comment by aii-guo** [comment]
> I have started to train this model on TF 1.12 after some modifications to the source code. With 16 batch size, I got around 11.5 mAP on COCO at 11 epoch. I am continuing the training process now.
hello,we meet the same problme
could you share where did you modifications to the code for tensorflow 1.12? 
thank you very much

**Comment by aii-guo** [comment]
> I have started to train this model on TF 1.12 after some modifications to the source code. With 16 batch size, I got around 11.5 mAP on COCO at 11 epoch. I am continuing the training process now.

hello,we meet the same problme
could you share where did you modifications to the code for tensorflow 1.12?
thank you very much

**Comment by moothes** [comment]
> 
> 
> > I have started to train this model on TF 1.12 after some modifications to the source code. With 16 batch size, I got around 11.5 mAP on COCO at 11 epoch. I am continuing the training process now.
> 
> hello,we meet the same problme
> could you share where did you modifications to the code for tensorflow 1.12?
> thank you very much

Emmmm...I modified the code for an experiment about two months ago, so I almost forgot the modifications.  I can give you the final code if you need it.

**Comment by aii-guo** [comment]
Yes, please share the final one
Thank you for your kind

moothes <notifications@github.com>于2020年6月19日 周五10:43写道：

**Comment by moothes** [comment]
[Code](https://github.com/moothes/EfficientDet-TF1.2). I modify this code to another project, you may need to optimize it.

**Comment by aii-guo** [comment]
> [Code](https://github.com/moothes/EfficientDet-TF1.2). I modify this code to another project, you may need to optimize it.


hello, thanks for you share!
I have tried your code in tensorflow1.12 environment 
but some error has happened 
when I run you code without any changes, it shows:

`TypeError: __call__() got an unexpected keyword argument 'partition_info'`

and I fixed it but other new error happen:

```
boxes = RegressBoxes(name='boxes')([anchors_input, regression[..., :4]])
  File "/opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 634, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "/opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorflow/python/autograph/impl/api.py", line 149, in wrapper
    raise e.ag_error_metadata.to_exception(type(e))
TypeError: in converted code:
    /Users/zhaozhen/work/eff_test/layers.py:108 call *
        return self.lmd(anchors, regression)
    TypeError: tf____call__() takes 2 positional arguments but 3 were given
```

it seems like a keras grammatical error, and fix it but other error happen:
```
ValueError: Layer lambda_1 was called with an input that isn't a symbolic tensor. Received type: <class 'numpy.ndarray'>. Full input: [array([[[ -12.       ,  -12.       ,   20.       ,   20.       ],
        [ -18.627417 ,   -7.3137083,   26.627417 ,   15.313708 ],
        [  -7.3137083,  -18.627417 ,   15.313708 ,   26.627417 ],
        ...,
        [  41.625336 ,   41.625336 ,  854.37463  ,  854.37463  ],
        [-126.70056  ,  160.64972  , 1022.70056  ,  735.3503   ],
        [ 160.64972  , -126.70056  ,  735.3503   , 1022.70056  ]]],
      dtype=float32), <tf.Tensor 'strided_slice:0' shape=(?, ?, 4) dtype=float32>]. All inputs to the layer should be tensors.
```

I have no idea how to solve this issue 
(by the way, when I try to saved the model of efficientdet rather than weight in tf1.14 also same error happened.)
do you have any idea of this ? 

thanks for you help!

**Comment by moothes** [comment]
The error means that the 'anchors_input' is a numpy array, you may need to convert it to a tf tensor.

I have uploaded a new version that running on our server. We use this code for training and inference on our own dataset. You can try the new code in the above URL.

**Comment by aii-guo** [comment]
thank you very much
I have tried your code and it and run well!
but you did not use prediction model here and use model to do the
evaluation after an epoch end
I have a question , which evaluation code are you using for your dataset ?
thank you again

2020年6月29日(月) 13:06 moothes <notifications@github.com>:

**Comment by aii-guo** [comment]
Hello, thank your quick reply very much !
and your new version code can work well in our dataset in
our environment (tensorflow=1.12, cuda=9.0)
but we just found the 1.12 version model's inference speed become almost 3
times slower than 1.14 version model
I think the main reason is that we only saved the train model  and not the
prediction model after one epoch.
That means we use the train model to do the prediction and need to do some
post processing after it (like nms).
This part will cost a lot of time compared to using a prediction model
directly like the 1.14 version did.
And I also know in 1.12 version we can not save the prediction model
directly after one epoch end.

Thus I want to know have you found the slower speed phenomenon in your test
and have you found some way to solve this problem ?

Thank you very much

Best regards

2020年6月29日(月) 13:06 moothes <notifications@github.com>:

**Comment by moothes** [comment]
I used this code for a simple project and move to other projects now. So no more optimization is applied to this code.
For the TF 1.14 version code, I remember that two layers in the testing phase are not suitable for TF 1.12. So I removed these layers and decoded the network outputs by a rough code, just to enable this code to work with TF 1.12.
If you want to improve the speed, you can try to implement a new decoding process or modify the above test layers to enable  TF1.12 testing.
