### ISSUE TITLE
I want to acess the layers of the Efficient-Net Backbone But I could not? 

### ISSUE THREAD

**Issue by bilel-bj** [xuannianz/EfficientDet#123]
I want to get access to the Efficient-Net Backbone and modify the name of some layers due to redundancy. But acctually it is a function not a model.
How to do that?

**Comment by xuannianz** [comment]
You can change the names even through they are in function.

**Comment by sinclairnick** [comment]
@bilel-bj in `model.py` look for the `features` variable
