### ISSUE TITLE
inference just won't predict anything

### ISSUE THREAD

**Issue by hareld10** [xuannianz/EfficientDet#126]
Hi,

model is being loaded and everything is O.K - until I get tensors back of (**,-1, **).

Someone got over it?

Best,

**Comment by xuannianz** [comment]
Hi @hareld10 , check this #108.

**Comment by elv-xuwen** [comment]
Hi, @xuannianz , @hareld10 I have the same issue. After using the solution in #108, I still have the problem. Can you tell me your solution if you solved it?

Best

**Comment by elv-xuwen** [comment]
Hi @hareld10 , I solved the issue by installing tensorflow==1.15 in a new environment. Hope this will help.

**Comment by hareld10** [comment]
@xuannianz @elv-xuwen installing the requirements solved it! thanks

**Comment by SiBensberg** [comment]
I reinstalled requirements and tensorflow==1.15 in a new environment. Sadly it does not change anything. Inference still not detecting anything. Did you retrain your model after creating the new environment?

**Comment by elv-xuwen** [comment]
Hi @hareld10 , did you test the inference time for a single image? It's 2 seconds/image for me, which is way longer than what the paper says. Do you have any idea of this?

**Comment by km23630** [comment]
> Hi @hareld10 , did you test the inference time for a single image? It's 2 seconds/image for me, which is way longer than what the paper says. Do you have any idea of this?

In my case inference speed was faster than yours.

this is my inference result.

GPU: tesla T4
model: coco-D0
batch_size: 0
`model.predict_on_batch` line spent 0.128832 sec (8 fps)

However, when I converted the model to tensorRT, it showed 131 fps at int8 batch_size 8.

**Comment by elv-xuwen** [comment]
Hi @km23630  Sorry, there was s typo. My inference time is 0.2 second/image. However, 0.12 second for batch_size==1 is still much longer than what in the paper. 
![image](https://user-images.githubusercontent.com/40640724/77995565-e2b56180-72e0-11ea-8301-4116028c5d2d.png)
In the paper, it's 16 ms/image.

**Comment by km23630** [comment]
> Hi @km23630 Sorry, there was a typo. My inference time is 0.2 second/image. However, 0.12 second for batch_size==1 is still much longer than what's in the paper.
> ![image](https://user-images.githubusercontent.com/40640724/77995565-e2b56180-72e0-11ea-8301-4116028c5d2d.png)
> In the paper, it's 16 ms/image.

they used TPU XD

**Comment by elv-xuwen** [comment]
> > Hi @km23630 Sorry, there was a typo. My inference time is 0.2 second/image. However, 0.12 second for batch_size==1 is still much longer than what's in the paper.
> > ![image](https://user-images.githubusercontent.com/40640724/77995565-e2b56180-72e0-11ea-8301-4116028c5d2d.png)
> > In the paper, it's 16 ms/image.
> 
> they used TPU XD

I think it says GPU latency. Can you tell me where in the paper it says they use TPU for inference? Thank you so much!

**Comment by km23630** [comment]
> > > Hi @km23630 Sorry, there was a typo. My inference time is 0.2 second/image. However, 0.12 second for batch_size==1 is still much longer than what's in the paper.
> > > ![image](https://user-images.githubusercontent.com/40640724/77995565-e2b56180-72e0-11ea-8301-4116028c5d2d.png)
> > > In the paper, it's 16 ms/image.
> > 
> > 
> > they used TPU XD
> 
> @km23630 , I think it says GPU latency. Can you tell me where in the paper it says they use TPU for inference? Thank you so much!

Sorry, It was my confusion.
paper's author inferenced with Titan V GPU.

![image](https://user-images.githubusercontent.com/30399899/77997838-1046ed00-736b-11ea-8e97-3d0ab8e90b87.png)

**Comment by elv-xuwen** [comment]
@km23630  Do you have any idea why the inference time doesn't match?

**Comment by elv-xuwen** [comment]
> > Hi @hareld10 , did you test the inference time for a single image? It's 2 seconds/image for me, which is way longer than what the paper says. Do you have any idea of this?
> 
> In my case inference speed was faster than yours.
> 
> this is my inference result.
> 
> GPU: tesla T4
> model: coco-D0
> batch_size: 0
> `model.predict_on_batch` line spent 0.128832 sec (8 fps)
> 
> However, when I converted the model to tensorRT, it showed 131 fps at int8 batch_size 8.

@km23630 Is is possible to share the converted tensorRT model with me? I had problem converting it. My email address is xs288@cornell.edu Thank you so much!

**Comment by km23630** [comment]
> > > Hi @hareld10 , did you test the inference time for a single image? It's 2 seconds/image for me, which is way longer than what the paper says. Do you have any idea of this?
> > 
> > 
> > In my case inference speed was faster than yours.
> > this is my inference result.
> > GPU: tesla T4
> > model: coco-D0
> > batch_size: 0
> > `model.predict_on_batch` line spent 0.128832 sec (8 fps)
> > However, when I converted the model to tensorRT, it showed 131 fps at int8 batch_size 8.
> 
> @km23630 Is is possible to share the converted tensorRT model with me? I had problem converting it. My email address is [xs288@cornell.edu](mailto:xs288@cornell.edu) Thank you so much!

please check your mail.

**Comment by lthbk5919** [comment]
@km23630 Can you share solution convert H5 to  tensorRT model?
