### ISSUE TITLE
Where to change `channels_first` 

### ISSUE THREAD

**Issue by prabindh** [xuannianz/EfficientDet#128]
#xuannianz Where is this "channels_first" to be changed ? I see only checks for channels_last like below

`if backend.image_data_format() == 'channels_last'`

Yes, it's normal. I did not know `channels_first` was faster. Interesting.

_Originally posted by @xuannianz in https://github.com/xuannianz/EfficientDet/issues/91#issuecomment-593682345_

**Comment by km23630** [comment]
To apply the above changes, the efficient-**Net** must be modified.
