### ISSUE TITLE
Can you trian the model with csv dataset successfully?

### ISSUE THREAD

**Issue by 2696120622** [xuannianz/EfficientDet#13]

**Comment by xuannianz** [comment]
Do you encounter any problems?

**Comment by 2696120622** [comment]
No, I want to train the model with csv dataset. However, the training example provided in this repository is for pascval dataset. I will have a try with csv dataset. Thank you for your great works.

**Comment by hoangminhtoan** [comment]
the script for using CSV file is the same in keras-retinanet.
"python train.py csv /path/to/csv/file/containing/annotations /path/to/csv/file/containing/classes"

**Comment by hoangminhtoan** [comment]
> No, I want to train the model with csv dataset. However, the training example provided in this repository is for pascal dataset. I will have a try with csv dataset. Thank you for your great works.

the script for using CSV file is the same as in keras-retinanet.
"python train.py csv /path/to/csv/file/containing/annotations /path/to/csv/file/containing/classes"

**Comment by 2696120622** [comment]
> > No, I want to train the model with csv dataset. However, the training example provided in this repository is for pascal dataset. I will have a try with csv dataset. Thank you for your great works.
> 
> the script for using CSV file is the same as in keras-retinanet.
> "python train.py csv /path/to/csv/file/containing/annotations /path/to/csv/file/containing/classes"

Thanks.
I can train with csv successfully.
