### ISSUE TITLE
Something is wrong when test the picture

### ISSUE THREAD

**Issue by devid1024** [xuannianz/EfficientDet#131]
ValueError: Layer #227 (named "BiFPN_0_P6_conv"), weight <tf.Variable 'BiFPN_0_P6_conv/kernel:0' shape=(3, 3, 320, 88) dtype=float32> has shape (3, 3, 320, 88), but the saved weight has shape (64, 320, 3, 3).

**Comment by SiBensberg** [comment]
you have to use the correct phi, weighted BiFPN and num_classes at the top of inference.py. As mentioned in #54

**Comment by devid1024** [comment]
ValueError: Layer #232 (named "fpn_cells/cell_0/fnode0/add") expects 1 weight(s), but the saved weights have 0 element(s).
I use the phi=0,and model_path = "pascal_47_1.1892_1.1196.h5" which is generated in checkpoints after the training is finished. By the way ,I chose the VOC2012 datasets and  classes = ['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'diningtable',
               'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor']

**Comment by SiBensberg** [comment]
I see you opened an new issue #138 for your problem. Can you close this one? :)
