### ISSUE TITLE
How can train this model with multi-gpu

### ISSUE THREAD

**Issue by angryhen** [xuannianz/EfficientDet#133]
Where should I modify the code

**Comment by SiBensberg** [comment]
You don't need to modify the code. Just modify the `--gpu 0` flag. Just add all gpus you want to use. For example `--gpu 0,1,2`

**Comment by nickkimer** [comment]
@SiBensberg I'm feeding the flag --gpu 0,1,2,3 but the usage across the 4 GPUs is 96%, 0%, 0%, and 0%. Is there any way to distribute the jobs? I'm using batch_size 4 with them as well

**Comment by SiBensberg** [comment]
I just trained a model once with 2 GPUs and didn't have a Problem. I am sorry, but I can't help you with that. The only thing I can tell you is I used tf==1.15 cuda10.0 and Cudnn==7.4.1.5

**Comment by vusraju** [comment]
I am also unable to do proper multi-gpu training. GPU usage is 0% for all GPUs expect the first GPU. Did anyone solve it? My environment is TF 2.1 and CUDA 10.1

Multi-GPU training is required for phi >= 3 in order to maintain higher batch size during training

**Comment by vusraju** [comment]
I hope this issue could be solved
