### ISSUE TITLE
Weights for bigger architecture? (D5, D6, D7)

### ISSUE THREAD

**Issue by hareld10** [xuannianz/EfficientDet#137]
Hi All,

If someone have weights to the slightly bigger arcs (D5, D6, D7 - I'd be extremely happy to get it!

Health to all,
Harel

**Comment by fitoule** [comment]
They are in the repo : https://storage.googleapis.com/cloud-tpu-checkpoints/efficientdet/coco/efficientdet-d7.tar.gz
