### ISSUE TITLE
TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

### ISSUE THREAD

**Issue by fuaiguo** [xuannianz/EfficientDet#139]
Hi, xuannianz:
         I use your new code (get compatible with both tf1 and tf2), but I have a new error, can you tell me the reason of this error?
Thanks!
@xuannianz

**Comment by nickkimer** [comment]
@xuannianz @fuaiguo I am also having this same error after 1 epoch completes

**Comment by tonnyzheng** [comment]
I am also having this same error after 1 epoch completes，do you have soloved？

**Comment by tonnyzheng** [comment]
> Hi, xuannianz:
> I use your new code (get compatible with both tf1 and tf2), but I have a new error, can you tell me the reason of this error?
> Thanks!
> @xuannianz

I am also having this same error after 1 epoch completes，do you have soloved？

**Comment by fuaiguo** [comment]
@nickkimer @tonnyzheng This error due to the farmat of model_output, you will conversion data format , and you can use the .numpy() in the eval/common.py

# run network
        boxes, scores, *_, labels = model.predict_on_batch([np.expand_dims(image, axis=0)])
        boxes = boxes.numpy() / scale   
        scores = scores.numpy()         
        labels = labels.numpy()        
        boxes[:, :, 0] = np.clip(boxes[:, :, 0], 0, w - 1)
        boxes[:, :, 1] = np.clip(boxes[:, :, 1], 0, h - 1)
        boxes[:, :, 2] = np.clip(boxes[:, :, 2], 0, w - 1)
        boxes[:, :, 3] = np.clip(boxes[:, :, 3], 0, h - 1)

I hope this can help you!
