### ISSUE TITLE
一个EfficientDet微信交流群

### ISSUE THREAD

**Issue by chunleiml** [xuannianz/EfficientDet#148]
![image](https://user-images.githubusercontent.com/29543941/79205370-6c803580-7e70-11ea-8bdb-22418f7ee4c6.png)

**Comment by Nioolek** [comment]
你好，二维码已过期，能否再发一次？

**Comment by chunleiml** [comment]
> 你好，二维码已过期，能否再发一次？

![image](https://user-images.githubusercontent.com/29543941/80072678-28301c00-8579-11ea-93fe-a207777deee1.png)
你好，上图是更新后的。

**Comment by QQ2737499951** [comment]
Tensorflow EfficientDet 深度学习实战群 755860371 共同学习，谢谢
