### ISSUE TITLE
Parameter counts are slightly off

### ISSUE THREAD

**Issue by noahtren** [xuannianz/EfficientDet#15]
Hi, thanks so much for creating this. EfficientDet looks really promising!

I ran your code and noticed that the parameter counts are slightly off compared to the official [paper](https://arxiv.org/abs/1911.09070). Here's a table below comparing what they reported in the paper and what this implementation produced. Any idea what could be causing this slight difference?

Model | Implementation | Official
-- | -- | --
B0 | 4.268788 | 3.9
B1 | 7.225352 | 6.6
B2 | 8.93297 | 8.1
B3 | 13.828736 | 12
B4 | 23.838512 | 20.7
B5 | 39.019592 | 33.7
B6 | 62.830688 | 51.9

Also, I noticed the authors added P6 and P7 layers that didn't exist in the original EfficientNet backbone. I'm thinking that this might have something to do with it.

**Comment by xuannianz** [comment]
Agree, let's wait for the official implementation.
