### ISSUE TITLE
How to train in Colab

### ISSUE THREAD

**Issue by uysalmustafa** [xuannianz/EfficientDet#153]
I've been trying to implement train Step 1 on Colab using:
`!python train.py --snapshot efficientdet-d0.h5 --phi 0 --gpu 0 --weighted-bifpn --random-transform --compute-val-loss --freeze-bn --batch-size 32 --steps 100 coco datasets/coco
`
But I get this error: 

```
Instructions for updating:
Please use Model.fit, which supports generators.
datasets/coco/images/train2017/i.rf.3f63f54866cc16e6b51fb2ea6c9bc5a3.jpg
Traceback (most recent call last):
  File "train.py", line 381, in <module>
    main()
  File "train.py", line 376, in main
    validation_data=validation_generator
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 1482, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 66, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py", line 818, in fit
    model=self)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 1112, in __init__
    model=model)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 908, in __init__
    **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 772, in __init__
    peek, x = self._peek_and_restore(x)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 912, in _peek_and_restore
    return x[0], x
  File "/content/drive/My Drive/EfficientDet-master/generators/common.py", line 424, in __getitem__
    inputs, targets = self.compute_inputs_targets(group)
  File "/content/drive/My Drive/EfficientDet-master/generators/common.py", line 373, in compute_inputs_targets
    image_group = self.load_image_group(group)
  File "/content/drive/My Drive/EfficientDet-master/generators/common.py", line 225, in load_image_group
    return [self.load_image(image_index) for image_index in group]
  File "/content/drive/My Drive/EfficientDet-master/generators/common.py", line 225, in <listcomp>
    return [self.load_image(image_index) for image_index in group]
  File "/content/drive/My Drive/EfficientDet-master/generators/coco.py", line 132, in load_image
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
cv2.error: OpenCV(4.1.2) /io/opencv/modules/imgproc/src/color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cvtColor'
```

Why I see this error?

**Comment by 2p990i9hpral** [comment]
check your file path
using os.isfile

**Comment by uysalmustafa** [comment]
> check your file path
> using os.isfile

```
import os
path = '/content/drive/My Drive/EfficientDet-master/datasets/coco/annotations/captions_train2017.json' 
isFile = os.path.isfile(path) 
print(isFile) 
```
 this returns `true`

[Here is folders ](https://imgur.com/a/1Ju5JG6)

**Comment by 2p990i9hpral** [comment]
> > check your file path
> > using os.isfile
> 
> ```
> import os
> path = '/content/drive/My Drive/EfficientDet-master/datasets/coco/annotations/captions_train2017.json' 
> isFile = os.path.isfile(path) 
> print(isFile) 
> ```
> 
> this returns `true`
> 
> [Here is folders ](https://imgur.com/a/1Ju5JG6)

hmm... check train.py execute parameters.

this is my parameter and structure.

```
Efficient_det\train.py
--snapshot
/workspace/secuwatcher-web/checkpoints/2020-04-13/coco_22_0.3164_0.3606.h5
--phi
0
--gpu
0
--weighted-bifpn
--random-transform
--compute-val-loss
--freeze-bn
--batch-size
16
--steps
1000
coco
/workspace/secuwatcher-web/Efficient_det/datasets/coco
```

![image](https://user-images.githubusercontent.com/30399899/79812823-f1a9a400-83b4-11ea-847a-d514ba4d66a2.png)

**Comment by uysalmustafa** [comment]
> hmm... check train.py execute parameters.
> 
> this is my parameter and structure.
> 
> ```
> Efficient_det\train.py
> --snapshot
> /workspace/secuwatcher-web/checkpoints/2020-04-13/coco_22_0.3164_0.3606.h5
> --phi
> 0
> --gpu
> 0
> --weighted-bifpn
> --random-transform
> --compute-val-loss
> --freeze-bn
> --batch-size
> 16
> --steps
> 1000
> coco
> /workspace/secuwatcher-web/Efficient_det/datasets/coco
> ```

Thanks. I've tried 
`!python train.py --snapshot efficientdet-d0.h5 --phi 0 --gpu 0 --weighted-bifpn --random-transform --compute-val-loss --freeze-bn --batch-size 32 --steps 100 coco datasets/coco`
But still same error. I've uploaded the whole traceback, can you look at it please?

**Comment by km23630** [comment]
> > hmm... check train.py execute parameters.
> > this is my parameter and structure.
> > ```
> > Efficient_det\train.py
> > --snapshot
> > /workspace/secuwatcher-web/checkpoints/2020-04-13/coco_22_0.3164_0.3606.h5
> > --phi
> > 0
> > --gpu
> > 0
> > --weighted-bifpn
> > --random-transform
> > --compute-val-loss
> > --freeze-bn
> > --batch-size
> > 16
> > --steps
> > 1000
> > coco
> > /workspace/secuwatcher-web/Efficient_det/datasets/coco
> > ```
> 
> Thanks. I've tried
> `!python train.py --snapshot efficientdet-d0.h5 --phi 0 --gpu 0 --weighted-bifpn --random-transform --compute-val-loss --freeze-bn --batch-size 32 --steps 100 coco datasets/coco`
> But still same error. I've uploaded the whole traceback, can you look at it please?

in your screen shot, 
you are using incorrect directory structure

set directory structure
datasets > coco > (annotations, images)

**Comment by 2p990i9hpral** [comment]
> > hmm... check train.py execute parameters.
> > this is my parameter and structure.
> > ```
> > Efficient_det\train.py
> > --snapshot
> > /workspace/secuwatcher-web/checkpoints/2020-04-13/coco_22_0.3164_0.3606.h5
> > --phi
> > 0
> > --gpu
> > 0
> > --weighted-bifpn
> > --random-transform
> > --compute-val-loss
> > --freeze-bn
> > --batch-size
> > 16
> > --steps
> > 1000
> > coco
> > /workspace/secuwatcher-web/Efficient_det/datasets/coco
> > ```
> 
> Thanks. I've tried
> `!python train.py --snapshot efficientdet-d0.h5 --phi 0 --gpu 0 --weighted-bifpn --random-transform --compute-val-loss --freeze-bn --batch-size 32 --steps 100 coco datasets/coco`
> But still same error. I've uploaded the whole traceback, can you look at it please?

Please check if the image exists

Image does not exist or the code is wrong.
Try printing the image_path used by imread()

**Comment by uysalmustafa** [comment]
> > > hmm... check train.py execute parameters.
> > > this is my parameter and structure.
> > > ```
> > > Efficient_det\train.py
> > > --snapshot
> > > /workspace/secuwatcher-web/checkpoints/2020-04-13/coco_22_0.3164_0.3606.h5
> > > --phi
> > > 0
> > > --gpu
> > > 0
> > > --weighted-bifpn
> > > --random-transform
> > > --compute-val-loss
> > > --freeze-bn
> > > --batch-size
> > > 16
> > > --steps
> > > 1000
> > > coco
> > > /workspace/secuwatcher-web/Efficient_det/datasets/coco
> > > ```
> > 
> > 
> > Thanks. I've tried
> > `!python train.py --snapshot efficientdet-d0.h5 --phi 0 --gpu 0 --weighted-bifpn --random-transform --compute-val-loss --freeze-bn --batch-size 32 --steps 100 coco datasets/coco`
> > But still same error. I've uploaded the whole traceback, can you look at it please?
> 
> Please check if the image exists
> 
> Image does not exist or the code is wrong.
> Try printing the image_path used by imread()

I've created train2017 under coco folder. Now it works. Thanks a lot!
