### ISSUE TITLE
Model hasnt converged...

### ISSUE THREAD

**Issue by init-22** [xuannianz/EfficientDet#158]
@SiBensberg I trained the model for  7.30 hours using Tesla K80 GPU on 2 classes with 2700 images and phi=0 with everything as a default setting with a batch size of 16, 168 steps and for 51 epochs, and ImageNet as a backbone, turns out that the model hasnt converged in that time. Do you think it would be better for me to train it with even more epochs? total loss was around 0.12 at that point and it wasn't changing much at that time since previous few epochs,  I think training more might lead to over-fitting since the loss is very low so I stopped at that point. Which parameters should change in this case? I think @km23630 @xuannianz  might also give better insights on this...

**Comment by northeastsquare** [comment]
Can you visualize your output on image during training, use tensorboard?

**Comment by northeastsquare** [comment]
set following visulize=True
EfficientDet/eval/common.py
def _get_detections(generator, model, score_threshold=0.05, max_detections=100, visualize=False):

**Comment by init-22** [comment]
@northeastsquare Thanks a lot, I'll try to visualize that....

**Comment by init-22** [comment]
@northeastsquare the loss was going down even after the last epoch,  I didnt see a flattened line there. I also saw that the model gives better accuracy and prediction at 25th epoch than 51 epochs but tensorboard doesnt seems to indicate that... seems like I still need to train more?
