### ISSUE TITLE
How to train EfficientDet-D6

### ISSUE THREAD

**Issue by yuyijie1995** [xuannianz/EfficientDet#16]
When I set Hyper parameter phi as 5 or 6 ,I found that I have to decrease the batchsize to a low value (because my gpu has only 11gb mem) . 
But after I modify the batchsize to 2 or 4 ,the model can not be trained normally,the loss can not decline and the eval ap is almost zero all the time. 
Can you give me some suggestions?

**Comment by xuannianz** [comment]
Add option `--freeze-bn` when the batch size is so small like 2 and 4.

**Comment by loki900718** [comment]
Same issue here. Have not been able to train with phi>=3, the regression head does not converge. @xuannianz Were you able to train D3 or above on VOC2007?
