### ISSUE TITLE
the error when i train

### ISSUE THREAD

**Issue by guangqianqin** [xuannianz/EfficientDet#162]
`# import keras
# import keras.preprocessing.image
# import keras.backend as K
# from keras.optimizers import Adam, SGD

from tensorflow import keras
import tensorflow.keras.backend as K
from tensorflow.keras.optimizers import Adam, SGD`

firstly, i get the path of keras by tf.keras.__path__, yet i cant train it .
so, `import keras
 import keras.preprocessing.image
 import keras.backend as K
 from keras.optimizers import Adam, SGD`
but it raise an error like this  `ValueError: Layer class_net was called with an input that isn't a symbolic tensor. Received type: <class 'int'>. Full input: [<tf.Tensor 'fpn_cells/cell_6/fnode3/op_after_combine8/bn/cond/Merge:0' shape=(?, 128, 128, 224) dtype=float32>, 0]. All inputs to the layer should be tensors.`

what should i do?

**Comment by northeastsquare** [comment]
Your input to the network is incorrect, not image, you can check it

**Comment by guangqianqin** [comment]
@northeastsquare  now,it raises another error .
`ValueError: Output tensors to a Model must be the output of a TensorFlow `Layer` (thus holding past layer metadata). Found: Tensor("filtered_detections/ma
p/TensorArrayStack/TensorArrayGatherV3:0", shape=(?, 100, 4), dtype=float32)`

my data type is csv , its like
 `('E:/Dataset/skating/2016\\500(1)-F-finalA\\img1/001360.jpg', [{'x
1': 1504, 'y1': 418, 'x2': 1549, 'y2': 476, 'class': 'athlete'}, {'x1': 1399, 'y1': 302, 'x2': 1438, 'y2': 355, 'class': 'athlete'}, {'x1': 1415, 'y1': 33
1, 'x2': 1465, 'y2': 381, 'class': 'athlete'}, {'x1': 1379, 'y1': 285, 'x2': 1422, 'y2': 338, 'class': 'athlete'}])`

is the version of tf not match?

**Comment by eypros** [comment]
Judging from my experience you probably are not using the correct tensorflow version. Try to stick with the requirements mentioned:
tensorflow 1.15 etc

**Comment by guangqianqin** [comment]
@eypros   @northeastsquare  ok,i correct it , tensorflow=1.15.0,the CUDA is 10.0 , cudnn is 7.4.2, i can run the code ,but it raises another error ` Unknown: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
         [[{{node stem_conv/Conv2D}}]]`,
 i used the default parms like batch_size=32. first, the GPU memory is enough , i used 2 tesla p100.if i should upgrade the version of cudnn to 7.5
