### ISSUE TITLE
having problem in inference quad

### ISSUE THREAD

**Issue by nimaone** [xuannianz/EfficientDet#165]
there are no offset_h and offset_w in utils.preprocess_image but they  used in inference_quad.py?!!

**Comment by northeastsquare** [comment]
just remove them

**Comment by nimaone** [comment]
@northeastsquare nothings happened when i remove them my result its like there is no NMS on image

**Comment by ConnorMcShane** [comment]
> there are no offset_h and offset_w in utils.preprocess_image but they used in inference_quad.py?!!

Did you figure this out? I am having this problem.
