### ISSUE TITLE
四边形预测，当物体是逆时针转了一点，效果很不好

### ISSUE THREAD

**Issue by northeastsquare** [xuannianz/EfficientDet#167]
看论文里面，计算是按照顺时针方向做的，实际测试如果是顺时针转了一点，效果还行，
但是物体只是逆时针转了一点，效果就不好，该如何改进？谢谢

**Comment by northeastsquare** [comment]
![image](https://user-images.githubusercontent.com/3086078/81470020-055d6300-921b-11ea-9cc5-053b7d69740d.png)

**Comment by northeastsquare** [comment]
![image](https://user-images.githubusercontent.com/3086078/81470088-62591900-921b-11ea-85d8-2af638c6c992.png)

**Comment by nimaone** [comment]
@northeastsquare How did you change inference quad to get this image?
my results are so dens in object and not accurate

**Comment by northeastsquare** [comment]
Just use this repo's code, not change can get this
