### ISSUE TITLE
Error in Train

### ISSUE THREAD

**Issue by ghali007** [xuannianz/EfficientDet#173]
when I trained using my dataset in COCO form, I obtained this error
**Error**: cv2.error: OpenCV(3.4.2) /io/opencv/modules/imgproc/src/color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper'

error line 113 eval/coco.py : image = **cv2.cvtColor(image, cv2.COLOR_BGR2RGB)**
how can I solve this problem.
thanks

**Comment by CraigWang1** [comment]
Usually when this happens to me it's because there's an error with the dataset path so opencv can't read the image. 

Maybe check your dataset path, make sure your data exists, and use direct paths (eg. /home/user/data/datset) instead of relative paths (eg. data/dataset)?

Hope this helps

**Comment by ghali007** [comment]
thanks
    Le vendredi 22 mai 2020 à 22:48:10 UTC+2, CraigWang1 <notifications@github.com> a écrit :  
 
 


Usually when this happens to me it's because there's an error with the dataset path so opencv can't read the image.

Maybe check your dataset path, make sure your data exists, and use direct paths (eg. /home/user/data/datset) instead of relative paths (eg. data/dataset)?

Hope this helps
