### ISSUE TITLE
Bad results for EfficientDetB0

### ISSUE THREAD

**Issue by longGGGGGG** [xuannianz/EfficientDet#18]
Hi.
When I downloaded your EfficientB0's pretrained model, and used for testing my own data, I get a very poor result. The boxes in the result are 300-dimensional list, and each score corresponds to box is greater than 0.9. Even if I set a very large score_threshold while filtering, most boxes will still be left. By drawing these boxes, I found that they are useless for detection.
I don't know what to do... Please help me.

**Comment by xuannianz** [comment]
Did you preprocess the image correctly before feed into the network?

**Comment by longGGGGGG** [comment]
Yeah, I just modify pathes of VOC2007 and checkpoints, and the value of phi.

**Comment by longGGGGGG** [comment]
> Did you preprocess the image correctly before feed into the network?

Yes, I just modify pathes of VOC2007 and checkpoints, and the value of phi.

**Comment by ZOUYIyi** [comment]
> Did you preprocess the image correctly before feed into the network?
> 
> Yes, I just modify pathes of VOC2007 and checkpoints, and the value of phi.

你解决这个问题了吗？
