### ISSUE TITLE
Bad mAP Performance 

### ISSUE THREAD

**Issue by fire717** [xuannianz/EfficientDet#180]
Same dataset(very easy task, just one class), 
I can get 0.98mAP in PyTorch version EfficientDet,
but use this TF version, can only get mAP aroud 0.6.

I trained in 2 steps like u write in readme, and have changed anchor ratio.
Thx.

**Comment by sonfire186** [comment]
What network and write your anchor ratio?

**Comment by fire717** [comment]
just d0， and anchor ratio was computed by [Anchor optimization](https://github.com/martinzlocha/anchor-optimization/)

**Comment by sonfire186** [comment]
And if you use `weighted_bifpn = True` when training?

**Comment by fire717** [comment]
> And if you use `weighted_bifpn = True` when training?

I'm not, just train as readme said:

```
STEP1: python3 train.py --snapshot imagenet --phi {0, 1, 2, 3, 4, 5, 6} --gpu 0 --random-transform --compute-val-loss --freeze-backbone --batch-size 32 --steps 1000 pascal|coco datasets/VOC2012|datasets/coco to start training. The init lr is 1e-3.
STEP2: python3 train.py --snapshot xxx.h5 --phi {0, 1, 2, 3, 4, 5, 6} --gpu 0 --random-transform --compute-val-loss --freeze-bn --batch-size 4 --steps 10000 pascal|coco datasets/VOC2012|datasets/coco to start training when val mAP can not increase during STEP1. The init lr is 1e-4 and decays to 1e-5 when val mAP keeps dropping down.
```

and I also tried use weighted_bifpn = True, got even worse result.

**Comment by sonfire186** [comment]
Try `--weighted-bifpn` for step 1

**Comment by tuvovan** [comment]
@fire717 how did you apply the generated anchor when training?
