### ISSUE TITLE
Large processing time 

### ISSUE THREAD

**Issue by sanazy** [xuannianz/EfficientDet#183]
I trained a model with my dataset using efficientdet 0. Although I got pretty good accuracy, I got large processing time (around 3 seconds for every test image) when using inference code. I thought efficientdet 0 must have very small processing time. Does anyone know is that normal or i made a mistake somewhere in code?

**Comment by KamalChhirang** [comment]
EfficientDet-D0 takes 16ms on my GPU (RTX 2070 Max Q) and around 160ms on CPU. It takes 3 seconds only when predicting on the first image. Can you share the code?

**Comment by sanazy** [comment]
You are right. I changed inference.py code such that it only processed 1 image at a time. I mean I eliminated this line of code :

`for image_path in glob.glob('datasets/VOC2007/JPEGImages/*.jpg'):`

As you said, I changed back the code so that a list of images went through the function and I got 3s for the first image and 0.2s for other ones.

Thanks alot for your help
