### ISSUE TITLE
I face the same problem after using the latest code.

### ISSUE THREAD

**Issue by fiyerowei** [xuannianz/EfficientDet#184]
I face the same problem after using the latest code @ csv mode.
The training process seems no problem.
however there's no inference result. (no matter how I try )
could any one give some suggestion about the no inference at all phenomena?

step1:
python train.py --snapshot imagenet --phi 0 --gpu 0,1 --random-transform --freeze-backbone --compute-val-loss --batch-size 2 --steps 200 csv D:\wordG.csv D:\wordG.txt --val-annotations-path D:\wordG.csv

step2:

python train.py --snapshot checkpoints\2020-06-19\csv_50_0.0043_0.7948.h5 --phi 0 --gpu 0,1 --random-transform --freeze-bn --compute-val-loss --batch-size 2 --steps 200 csv D:\wordG.csv D:\wordG.txt --val-annotations-path D:\wordG.csv

Epoch 00042: saving model to checkpoints/2020-06-19\csv_42_0.0081_0.2341.h5
200/200 [==============================] - 168s 840ms/step - loss: 0.0081 - classification_loss: 0.0021 - regression_loss: 0.0059 - val_loss: 0.2341 - val_classification_loss: 0.2016 - val_regression_loss: 0.0326
Epoch 43/50
199/200 [============================>.] - ETA: 0s - loss: 0.0065 - classification_loss: 0.0013 - regression_loss: 0.0052Epoch 1/50
245/200 [====================================] - 24s 99ms/step - loss: 0.2023 - classification_loss: 0.2089 - regression_loss: 0.0304
Running network: 100% (489 of 489) |##############################################################################################| Elapsed Time: 0:00:26 Time:  0:00:26
Parsing annotations: 100% (489 of 489) |##########################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
num_fp=34253.0, num_tp=2745.0
199 instances of class 0 with average precision: 0.8843
136 instances of class 1 with average precision: 0.8379
204 instances of class 2 with average precision: 0.9671
267 instances of class 3 with average precision: 0.9180
78 instances of class 4 with average precision: 0.7325
417 instances of class 5 with average precision: 0.9871
184 instances of class 6 with average precision: 1.0000
72 instances of class 7 with average precision: 1.0000
2 instances of class 8 with average precision: 1.0000
498 instances of class 9 with average precision: 0.9989
23 instances of class A with average precision: 0.0855
340 instances of class C with average precision: 0.9917
23 instances of class K with average precision: 1.0000
23 instances of class L with average precision: 1.0000
320 instances of class R with average precision: 0.9190
2 instances of class T with average precision: 1.0000
1 instances of class U with average precision: 1.0000
1 instances of class V with average precision: 1.0000
1 instances of class X with average precision: 0.0048
mAP: 0.8593

Epoch 00043: saving model to checkpoints/2020-06-19\csv_43_0.0065_0.2393.h5
200/200 [==============================] - 168s 841ms/step - loss: 0.0065 - classification_loss: 0.0013 - regression_loss: 0.0052 - val_loss: 0.2393 - val_classification_loss: 0.2089 - val_regression_loss: 0.0304
Epoch 44/50
104/200 [==============>...............] - ETA: 56s - loss: 0.0054 - classification_loss: 7.3843e-04 - regression_loss: 0.0046Traceback (most recent call last):.

_Originally posted by @fiyerowei in https://github.com/xuannianz/EfficientDet/issues/117#issuecomment-646406922_

**Comment by KamalChhirang** [comment]
The problem is in Inference right? 

Can you tell me your Tensorflow version & maybe share Inference code?

**Comment by fiyerowei** [comment]
Please help.
I use python36.
Below is my TF version.
tensorboard                   1.15.0
tensorflow-estimator     1.15.1
tensorflow-gpu              1.15.0


I use the inference.py
but the ouput box,score,label are all -1 printed
//////////////////////////////////////////////////////////////////////////////import cv2
import json
import numpy as np
import os
import time
import glob

from model import efficientdet
from utils import preprocess_image, postprocess_boxes
from utils.draw_boxes import draw_boxes


def main():
    phi = 1
    weighted_bifpn = False;
    model_path = 'checkpoints/2020-06-18/csv_18_0.0225.h5'
    image_sizes = (512, 640, 768, 896, 1024, 1280, 1408)
    image_size = image_sizes[phi]
    # coco classes
    classes = ['0','1','2','3','4','5','6','7','8','9','A','C','K','L','R','T','U','V','X']
    num_classes = len(classes)    
    #classes = {value['id'] - 1: value['name'] for value in json.load(open('coco_90.json', 'r')).values()}    
    #num_classes = 90
    score_threshold = 0.3
    colors = [np.random.randint(0, 256, 3).tolist() for _ in range(num_classes)]
    _, model = efficientdet(phi=phi,
                            weighted_bifpn=weighted_bifpn,
                            num_classes=num_classes,
                            score_threshold=score_threshold)
    model.load_weights(model_path, by_name=True)

    for image_path in glob.glob('D:/Fiyero_Test/word_with_G/*.bmp'):
        image = cv2.imread(image_path)
        src_image = image.copy()
        # BGR -> RGB
        image = image[:, :, ::-1]
        h, w = image.shape[:2]

        image, scale ,offset_h, offset_w= preprocess_image(image, image_size=image_size)
        # run network
        start = time.time()
        boxes, scores, labels = model.predict_on_batch([np.expand_dims(image, axis=0)])
        boxes, scores, labels = np.squeeze(boxes), np.squeeze(scores), np.squeeze(labels)
        print(time.time() - start)
        boxes = postprocess_boxes(boxes=boxes, scale=scale, height=h, width=w)
        print(boxes)
        print(scores)
        # select indices which have a score above the threshold
        indices = np.where(scores[:] > score_threshold)[0]

        # select those detections
        boxes = boxes[indices]
        labels = labels[indices]

        draw_boxes(src_image, boxes, scores, labels, colors, classes)

        cv2.namedWindow('image', cv2.WINDOW_NORMAL)
        cv2.imshow('image', src_image)
        cv2.waitKey(0)


if __name__ == '__main__':
    main()

**Comment by fiyerowei** [comment]
I work @ Win10 system with cuda10     RTX-2080Ti X2 

below are my installing

absl-py==0.9.0
alabaster==0.7.12
albumentations==0.4.2
astor==0.8.1
astroid==2.4.1
atomicwrites==1.4.0
attrs==19.3.0
autopep8==1.5.3
Babel==2.8.0
backcall==0.1.0
bcrypt==3.1.7
bleach==3.1.5
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
cloudpickle==1.4.1
colorama==0.4.3
cryptography==2.9.2
cycler==0.10.0
Cython==0.29.19
decorator==4.4.2
defusedxml==0.6.0
diff-match-patch==20181111
docutils==0.16
entrypoints==0.3
flake8==3.8.2
gast==0.2.2
google-pasta==0.2.0
grpcio==1.29.0
h5py==2.10.0
helpdev==0.7.1
idna==2.9
imageio @ file:///C:/Users/Administrator/AppData/Local/Programs/Python/Python36/Scripts/imageio-2.5.0-py3-none-any.whl
imagesize==1.2.0
imgaug==0.2.6
importlib-metadata==1.6.0
intervaltree==3.0.2
ipykernel==5.3.0
ipython==7.15.0
ipython-genutils==0.2.0
isort==4.3.21
jedi==0.15.2
Jinja2==2.11.2
jsonschema==3.2.0
jupyter-client==6.1.3
jupyter-core==4.6.3
Keras @ file:///D:/User/Fiyero/EfficientDet-master_New/Keras-2.2.5-py2.py3-none-any.whl
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
# Editable install with no version control (keras-resnet==0.1.0)
-e d:\user\fiyero\keras-resnet-0.1.0
keyring==21.2.1
kiwisolver==1.2.0
lazy-object-proxy==1.4.3
Markdown==3.2.2
MarkupSafe==1.1.1
matplotlib==3.2.1
mccabe==0.6.1
mistune==0.8.4
nbconvert==5.6.1
nbformat==5.0.6
networkx @ file:///C:/Users/Administrator/AppData/Local/Programs/Python/Python36/Scripts/networkx-2.4-py3-none-any.whl
numpy==1.18.5
numpydoc==1.0.0
opencv-contrib-python @ file:///C:/Users/Administrator/AppData/Local/Programs/Python/Python36/Scripts/opencv_contrib_python-3.4.2.17-cp36-cp36m-win_amd64.whl
opencv-python @ file:///C:/Users/Administrator/AppData/Local/Programs/Python/Python36/Scripts/opencv_python-3.4.2.17-cp36-cp36m-win_amd64.whl
opt-einsum==3.2.1
packaging==20.4
pandocfilters==1.4.2
paramiko==2.7.1
parso==0.5.2
pathtools==0.1.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==6.2.0
pluggy==0.13.1
progressbar2==3.51.3
prompt-toolkit==3.0.5
protobuf==3.12.2
psutil==5.7.0
ptyprocess==0.6.0
pycodestyle==2.6.0
pycparser==2.20
pydocstyle==5.0.2
pyflakes==2.1.1
Pygments==2.6.1
pylint==2.5.2
PyNaCl==1.4.0
pyparsing==2.4.7
PyQt5==5.12.3
PyQt5-sip==12.8.0
PyQtWebEngine==5.12.1
pyrsistent==0.16.0
python-dateutil==2.8.1
python-jsonrpc-server==0.3.4
python-language-server==0.31.10
python-utils==2.4.0
pytz==2020.1
PyWavelets @ file:///C:/Users/Administrator/AppData/Local/Programs/Python/Python36/Scripts/PyWavelets-1.0.3-cp36-none-win_amd64.whl
pywin32==227
pywin32-ctypes==0.2.0
PyYAML @ file:///C:/Users/Administrator/AppData/Local/Programs/Python/Python36/Scripts/PyYAML-5.2-cp36-cp36m-win_amd64.whl
pyzmq==19.0.1
QDarkStyle==2.8.1
QtAwesome==0.7.2
qtconsole==4.7.4
QtPy==1.9.0
requests==2.23.0
rope==0.17.0
scikit-image @ file:///C:/Users/Administrator/AppData/Local/Programs/Python/Python36/Scripts/scikit_image-0.14.5-cp36-none-win_amd64.whl
scipy==1.4.1
six==1.15.0
snowballstemmer==2.0.0
sortedcontainers==2.1.0
Sphinx==3.0.4
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
spyder==4.1.3
spyder-kernels==1.9.1
tensorboard==1.15.0
tensorflow-estimator==1.15.1
tensorflow-gpu==1.15.0
termcolor==1.1.0
testpath==0.4.4
toml==0.10.1
tornado==6.0.4
tqdm==4.28.1
traitlets==4.3.3
typed-ast==1.4.1
urllib3==1.25.9
watchdog==0.10.2
wcwidth==0.2.3
webencodings==0.5.1
Werkzeug==1.0.1
wrapt==1.12.1
yapf==0.30.0

**Comment by KamalChhirang** [comment]
I assume you are not using the lastest code because of this line:

`  image, scale ,offset_h, offset_w= preprocess_image(image, image_size=image_size)
`
Preprocess_image function just returns image and scale now. 

Try to download the code again, and run inference.py with your trained model. It should work.

**Comment by fiyerowei** [comment]
Very thanks for your help.
After I do some experiment after using the latest code (just downloaded and don't change any setting), I come out the conclusion that if I use **phi>3** **model** (EX:4,5,6) it works well ; but others **phi <=3** **model** training process seems good but still no boxes detected.

**Comment by KamalChhirang** [comment]
> Very thanks for your help.
> After I do some experiment after using the latest code (just downloaded and don't change any setting), I come out the conclusion that if I use **phi>3** **model** (EX:4,5,6) it works well ; but others **phi <=3** **model** training process seems good but still no boxes detected.

It should not happen. I used phi=2 before few days ago, and it worked well. Try using one of the pretrained model for phi (0,1,2,3) maybe.

**Comment by ijazakhter** [comment]
I am facing the same issue, tried several images from VOC  with all phis from {1:4} but not getting any boxes. I am using your pretrained models.

**Comment by adarsh0906** [comment]
https://github.com/google/automl/issues/521 check this issue in original code  it might cause the issue

**Comment by Allaye** [comment]
@fiyerowei  for your training what arguments did you use am having the pre-trained model, now I want to continue from where it stops. which options am i to use? thanks
