### ISSUE TITLE
Error running training step 2

### ISSUE THREAD

**Issue by bc-bytes** [xuannianz/EfficientDet#187]
Step 1 runs fine, but I am getting the following error on step 2:

```
Loading model, this may take a second...
Traceback (most recent call last):
  File "train.py", line 381, in <module>
    main()
  File "train.py", line 333, in main
    model.load_weights(args.snapshot, by_name=True)
  File "/home/bc/anaconda3/envs/dfu/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 182, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/bc/anaconda3/envs/dfu/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/network.py", line 1371, in load_weights
    saving.load_weights_from_hdf5_group_by_name(f, self.layers)
  File "/home/bc/anaconda3/envs/dfu/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 754, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #1 (named "stem_conv"), weight <tf.Variable 'stem_conv/kernel:0' shape=(3, 3, 3, 32) dtype=float32> has shape (3, 3, 3, 32), but the saved weight has shape (64, 3, 3, 3)
```

Anyone have any idea what the issue might be?

**Comment by bc-bytes** [comment]
I downloaded the weights from here: https://www.kaggle.com/chopinforest1986/efficientnetb0b7-keras-weights/data

And this is the command I used for step 2:

`
python train.py --snapshot model/efficientnet-b7_weights_tf_dim_ordering_tf_kernels_autoaugment_notop.h5 --phi 0 --gpu 0 --random-transform --compute-val-loss --freeze-bn --batch-size 4 --steps 1000 csv train_data/train_annotations.csv train_data/train_class.csv --val-annotations-path train_data/val_annotations.csv`

**Comment by Allaye** [comment]
@bc-bytes did you find any saved model after the first training?

**Comment by bc-bytes** [comment]
@Allaye Step 1 created checkpoints in the checkpoints folder. Am I meant to use one of those checkpoints with step 2?

**Comment by Allaye** [comment]
Yes i think so, but i am not even able to get those checkpoint to save

**Comment by bc-bytes** [comment]
@Allaye I had no problems with step 1. What is the error you are getting?

**Comment by bc-bytes** [comment]
I am currently around 3 days into running step 2, with about 4 days remaining. However, I am concerned about the results it reports after each epoch:

```
Running network: 100% (386 of 386) |#####| Elapsed Time: 0:00:29 Time:  0:00:29
Parsing annotations: 100% (386 of 386) |#| Elapsed Time: 0:00:00 Time:  0:00:00
num_fp=0, num_tp=0
500 instances of xxxx with average precision: 0.0000
mAP: 0.0000

Epoch 00016: mAP did not improve from 0.00000
10000/10000 [==============================] - 12722s 1s/step - loss: 6.5130 - regression_loss: 2.6568 - classification_loss: 3.8559 - val_loss: 6.5145 - val_regression_loss: 2.6583 - val_classification_loss: 3.8562
Epoch 17/50
    1/10000 [..............................] - ETA: 3:32:49 - loss: 6.3790 - reg
```
This bit: "Epoch 00016: mAP did not improve from 0.00000" does not look correct, especially at epoch 16/50. Am I reading that wrong, or does it look like step 2 is not training correctly?

**Comment by bc-bytes** [comment]
I reduced the number of steps, and it seems to be working OK now.

**Comment by bc-bytes** [comment]
I spoke too soon... I reduced the number of steps to 100, but after the first few epochs, mAP falls to 0.0 and stays at that value for subsequent epochs.
