### ISSUE TITLE
Is possible to deploy EfficientDet in mobile ?

### ISSUE THREAD

**Issue by Papaass** [xuannianz/EfficientDet#2]

**Comment by xuannianz** [comment]
Sure. As the paper lists, both the #Params and #FLOPS are much fewer than other object detectors.

**Comment by Papaass** [comment]
Thanks.
We can do it with tflite ?

**Comment by xuannianz** [comment]
I have not worked on tf lite so far, so I can not give you an answer.
Maybe you need to convert the weights to adapt to your models on tf-lite.

**Comment by Papaass** [comment]
Ok. thanks again. I wiil try

**Comment by 2696120622** [comment]
> Ok. thanks again. I wiil try

Have  you deployed EfficientDet in mobile?
If sure, which EfficientDet model did you choose?

**Comment by ac4391** [comment]
Would be interested in using efficientdet on mobile with tflite. However I am not sure that tensorflow object detection API allow models other than SSD based for tflite. Does anyone tried running efficientdet on mobile?
