### ISSUE TITLE
Incompatible shape in inference

### ISSUE THREAD

**Issue by gan-xiao-nan** [xuannianz/EfficientDet#213]
ValueError: Layer #810 (named "box_net/box-predict"), weight <tf.Variable 'box_net/box-predict/pointwise_kernel:0' shape=(1, 1, 224, 36) dtype=float32,numpy=
array([[[[-0.04699235, -0.02564223,  0.00853208, ..., -0.0246127 ,
           0.08096791, -0.02760192],
         [ 0.03991835,  0.06335132, -0.06923918, ...,  0.07520743,
           0.09410413, -0.00520394],
         [ 0.12037021,  0.03845677, -0.00221151, ..., -0.01830149,
           0.07997871, -0.0675458 ],
         ...,
         [ 0.07699301, -0.00094294, -0.00162442, ...,  0.05020301,
          -0.08706699, -0.12831083],
         [ 0.11896881,  0.05107141, -0.08757737, ..., -0.05650857,
           0.02637086, -0.0718085 ],
         [ 0.01957712, -0.10257559,  0.04454782, ...,  0.05055531,
          -0.05182468, -0.02485939]]]], dtype=float32)> has shape (1, 1, 224, 36), but the saved weight has shape (1, 1, 224, 81).

Anyone know how to solve this? I change the number of classes from 90 to 1 in inference

**Comment by jorie-peng** [comment]
phi must match model, if phi is 3,you must use pretrained model efficientnet-b3
