### ISSUE TITLE
Where to find function postprocess_boxes

### ISSUE THREAD

**Issue by gan-xiao-nan** [xuannianz/EfficientDet#215]
May I ask, in inference.py, where should we find the postprocess_boxes() function? Based on 'from utils import preprocess_image, postprocess_boxes' in inference.py, there should be a python file contain the postprocess_boxes() function, but i cant see it, or inside utils folder also do not contain that postprocess_boxes function/file?

**Comment by DujeMedak** [comment]
Hi, I think the function you are searching for is located inside the __init__.py file inside the utils directory. (__init__.py files usually don't contain function definitions so I guess that is why you forgot to look there).
