### ISSUE TITLE
ValueError: Layer #329

### ISSUE THREAD

**Issue by pouriamsz** [xuannianz/EfficientDet#216]
hi guys can you help me plz 
I am a newbie. I have a terrible GPU. So I've been trying to learn how to use Google Colab
when i use inference_quad.py for efficientdet-d0 so i changed phi from 3 to 0 and just run it ... and i got this error ! 

ValueError: Layer #329 (named "resample p6/conv 2d"), weight <tf.Variable 'resample p6/conv2d_10/kernel:0' shape=(1, 1, 320, 64) dtype=float32> has shape (1, 1, 320, 64), but the saved weight has shape (88, 320, 1, 1).

**Comment by cyrilzakka** [comment]
How did you fix this error?
