### ISSUE TITLE
TF2.3.0 Error while Training - ValueError: It appears you are trying to construct a functional model, but not all of the inputs in the first positional argument of your layer call are symbolic tensors. (Input objects, or the output of another layer) Functional models cannot correctly track custom layers unless all values in the first call argument are symbolic.

### ISSUE THREAD

**Issue by vis55** [xuannianz/EfficientDet#225]
Traceback (most recent call last):
  File "train.py", line 381, in <module>
    main()
  File "train.py", line 318, in main
    detect_quadrangle=args.detect_quadrangle
  File "/content/EfficientDet/model.py", line 445, in efficientdet
    classification = [class_net([feature, i]) for i, feature in enumerate(fpn_features)]
  File "/content/EfficientDet/model.py", line 445, in <listcomp>
    classification = [class_net([feature, i]) for i, feature in enumerate(fpn_features)]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 924, in __call__
    if _in_functional_construction_mode(self, inputs, args, kwargs, input_list):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer.py", line 3223, in _in_functional_construction_mode
    raise ValueError('It appears you are trying to construct a '
ValueError: It appears you are trying to construct a functional model, but not all of the inputs in the first positional argument of your layer call are symbolic tensors. (Input objects, or the output of another layer) Functional models cannot correctly track custom layers unless all values in the first call argument are symbolic.

I used the following to start training. 
 "!python3 train.py --snapshot imagenet --phi 1 --gpu 0 \
--random-transform --compute-val-loss --freeze-backbone --batch-size 32 --steps 1000 coco cocodata
"
Training on :MSCOCO dataset. 
Using: Google colab

Additional Info: This error happens when I use tensorflow2.3.0 but works well for tensorflow2.1.0.

**Comment by TheAptic** [comment]
I had the same issue, downgrading to tensorflow 1.15 fixes the issue. however I tried using the inferences_video.py to get some results from this model and all boxes and scores are arrays with all values of -1.
