### ISSUE TITLE
Error while loading .c cython file in anchors.py. Already ran setup.py still getting following.

### ISSUE THREAD

**Issue by sanjaydeo96** [xuannianz/EfficientDet#231]
![Screenshot from 2021-01-12 20-04-28](https://user-images.githubusercontent.com/29541116/104328205-9c4c8e80-5511-11eb-94cd-d35a754cbc51.png)

**Comment by Muhammad-Ahmad-Waseem** [comment]
Hey @sanjaydeo96, I am facing the same issue. Were you able to solve it? If yes, can you guide me?

**Comment by Muhammad-Ahmad-Waseem** [comment]
Update:

If anyone is facing this issue, kindly add these lines before importing utils.compute_overlap in utils/anchors.py

import pyximport
pyximport.install()

This solved the issue in my case.
