### ISSUE TITLE
No visible results on evaluation

### ISSUE THREAD

**Issue by rafiei91** [xuannianz/EfficientDet#241]
I have trained the model for COCO dataset by phi=0 and then execute the evaluation. The process goes until the end and finishes without any error. But, I can not see the results regarding the evaluation, such as AP.
Is there any specific place or code to see them?

**Comment by VeereshVS** [comment]
You can evaluate the trained model using eval/coco.py

**Comment by rafiei91** [comment]
> You can evaluate the trained model using eval/coco.py

Yes, I executed that, and it goes well, but no results.
