### ISSUE TITLE
is there any way to change model parameters and use pretrained weights?

### ISSUE THREAD

**Issue by robosina** [xuannianz/EfficientDet#25]
I want to decrease size of the network for an specific project!! is this possible to change network parameters?

**Comment by xuannianz** [comment]
Sure, you need to finetune after loading pretrained weights.

**Comment by 2696120622** [comment]
> I want to decrease size of the network for an specific project!! is this possible to change network parameters?

Hello, could you share your way of decreasing size of the network?
What is the size of your model?

**Comment by robosina** [comment]
@2696120622 it is exactly my question!! for now I'm working on another project so if I get any helpful result I will share with you

**Comment by 2696120622** [comment]
> @2696120622 it is exactly my question!! for now I'm working on another project so if I get any helpful result I will share with you

OK.
Thanks!
I have trained a EfficientDet-D1 with 29MB parameter file.
I want to apply it to mobile phone, but I don't know how to do it and if this size is too large to deploy.

**Comment by robosina** [comment]
@2696120622 , Honestly I don't know exactly how to do it, because at this time I'm working on another project so  the Owner of the project is the best person to answer this question,Sorry for late answer.
