### ISSUE TITLE
How to add rotation to the model ?

### ISSUE THREAD

**Issue by jamessmith90** [xuannianz/EfficientDet#26]
I have a dataset that i would like to train but i would my requirements are a bit different than simple plain boxes. I have some objects that are to be detected with rotation. So what changes can i make to add this functionality in the architecture ?

**Comment by xuannianz** [comment]
https://arxiv.org/abs/1704.03155 this paper may inspire you even though it's about text detection.

**Comment by jamessmith90** [comment]
I have gone through these papers and i need that extra 10% accuracy which i am sure EfficientDet-B7 will give me because its the most accurate on imagenet but i need changes in the detection module for rotation. Can you provide some knowledge on how to proceed for this ?
