### ISSUE TITLE
import error in windows: ModuleNotFoundError: No module named 'utils.compute_overlap'

### ISSUE THREAD

**Issue by 2696120622** [xuannianz/EfficientDet#28]
from utils.compute_overlap import compute_overlap
When I run this import statement in windows, I get ModuleNotFoundError: No module named 'utils.compute_overlap'.
How to fix this error?

**Comment by tinghaoyu** [comment]
utils/anchors.py
`
import pyximport
pyximport.install()
`

**Comment by tinghaoyu** [comment]
> from utils.compute_overlap import compute_overlap
> When I run this import statement in windows, I get ModuleNotFoundError: No module named 'utils.compute_overlap'.
> How to fix this error?
utils/anchors.py
`import pyximport`
`pyximport.install()`

**Comment by 2696120622** [comment]
> > from utils.compute_overlap import compute_overlap
> > When I run this import statement in windows, I get ModuleNotFoundError: No module named 'utils.compute_overlap'.
> > How to fix this error?
> > utils/anchors.py
> > `import pyximport`
> > `pyximport.install()`

Thanks.
I add
import pyximport
pyximport.install()
in utils/anchors.py
However, I encounter another ImportError as follows
ImportError: Building module utils.compute_overlap failed: ["distutils.errors.CompileError: command 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio 14.0\\\\VC\\\\BIN\\\\x86_amd64\\\\cl.exe' failed with exit status 2\n"]

**Comment by drorhilman** [comment]
try renaming "utils/compute_overlap.cpython-36m-x86_64-linux-gnu.so" to compute_overlap.c

**Comment by 2696120622** [comment]
This error has been solved by copying compute_overlap.c and compute_overlap.cp36-win_amd64.pyd from keras-retinanet/keras_retinanet/utils in keras-retinanet to EfficientDet/utils.

**Comment by ahmad-learn** [comment]
> This error has been solved by copying compute_overlap.c and compute_overlap.cp36-win_amd64.pyd from keras-retinanet/keras_retinanet/utils/ in fizyr/keras-retinanet to EfficientDet/utils/.

hi
i did this work but didn't solve this problem

**Comment by 2696120622** [comment]
``

> > This error has been solved by copying compute_overlap.c and compute_overlap.cp36-win_amd64.pyd from keras-retinanet/keras_retinanet/utils/ in fizyr/keras-retinanet to EfficientDet/utils/.
> > thanks
> > but
> > i did this work but didn't solve this problem

It works for me.
Maybe, you can
import pyximport
pyximport.install()
in utils/anchors.py as a try.

**Comment by wzs9717** [comment]
rename compute_overlap.cpython-36m-x86_64-linux-gnu.so to compute_overlap.so can solve this problem. You can learn it from Cpython.

**Comment by bill2239** [comment]
> This error has been solved by copying compute_overlap.c and compute_overlap.cp36-win_amd64.pyd from keras-retinanet/keras_retinanet/utils/ in fizyr/keras-retinanet to EfficientDet/utils/.


couldn't find compute_overlap.cp36-win_amd64.pyd in fizyr/keras-retinanet

**Comment by xuannianz** [comment]
#89 @bill2239

**Comment by bc-bytes** [comment]
@xuannianz I tried all the fixes in this thread, and tried running setup.py (which ran without errors) but I am still getting this error:

```
from utils.compute_overlap import compute_overlap
ModuleNotFoundError: No module named 'utils'
```

**Comment by Gokul14092001** [comment]
> > > from utils.compute_overlap import compute_overlap
> > > When I run this import statement in windows, I get ModuleNotFoundError: No module named 'utils.compute_overlap'.
> > > How to fix this error?
> > > utils/anchors.py
> > > `import pyximport`
> > > `pyximport.install()`
> 
> Thanks. I add import pyximport pyximport.install() in utils/anchors.py However, I encounter another ImportError as follows ImportError: Building module utils.compute_overlap failed: ["distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2\n"]

how to fix this error?I'm training on windows

**Comment by chelw97** [comment]
您好，我已收到您的邮件，会尽快回复。

**Comment by Gokul14092001** [comment]
> > > from utils.compute_overlap import compute_overlap
> > > When I run this import statement in windows, I get ModuleNotFoundError: No module named 'utils.compute_overlap'.
> > > How to fix this error?
> > > utils/anchors.py
> > > `import pyximport`
> > > `pyximport.install()`
> 
> Thanks. I add import pyximport pyximport.install() in utils/anchors.py However, I encounter another ImportError as follows ImportError: Building module utils.compute_overlap failed: ["distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2\n"]

This Building module error can be solve by running setup.py Example:setup.py build_ext --inplace
