### ISSUE TITLE
Documentation required for the engineering environment

### ISSUE THREAD

**Issue by tensorflowt** [xuannianz/EfficientDet#3]
Hello! When I rediscovered your project, I encountered the following problem：
` File "/media/zhangwentao/DATA1/Documents2/Project-DL/EfficientDet-master/model.py", line 162, in efficientdet
    class_head = build_class_head(w_head, d_head, num_classes=num_classes)
  File "/media/zhangwentao/DATA1/Documents2/Project-DL/EfficientDet-master/model.py", line 138, in build_class_head
    )(outputs)`
`TypeError: __call__() got an unexpected keyword argument 'partition_info'`

, which I preliminarily judged to be the problem of tf version. Therefore, I would like to communicate with you. What is the basic environment required for your project？

Could you please provide yours requirements.txt?

thanks.

**Comment by xuannianz** [comment]
Hi, the file is uploaded.
