### ISSUE TITLE
Retrain model，num_fp=0, num_tp=0

### ISSUE THREAD

**Issue by HaiLongEmb** [xuannianz/EfficientDet#30]
@xuannianz 
I retrain the model，get 0.000. Please help me, boss
Running network: 100% (1279 of 1279) |##########################################################################################| Elapsed Time: 0:02:15 Time:  0:02:15
Parsing annotations: 100% (1279 of 1279) |######################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
num_fp=0, num_tp=0
3076 instances of class person with average precision: 0.0000
937 instances of class person_1 with average precision: 0.0000
4007 instances of class body with average precision: 0.0000

**Comment by balag59** [comment]
> @xuannianz
> I retrain the model，get 0.000. Please help me, boss
> Running network: 100% (1279 of 1279) |##########################################################################################| Elapsed Time: 0:02:15 Time: 0:02:15
> Parsing annotations: 100% (1279 of 1279) |######################################################################################| Elapsed Time: 0:00:00 Time: 0:00:00
> num_fp=0, num_tp=0
> 3076 instances of class person with average precision: 0.0000
> 937 instances of class person_1 with average precision: 0.0000
> 4007 instances of class body with average precision: 0.0000

I had a similar issue while training with my own csv dataset.On someone's suggestion here I tried using the exact same versions of keras and tf mentioned below and it seemed to work:
tensorflow 1.15.0
Keras 2.2.5
Keras-Applications 1.0.8
Keras-Preprocessing 1.1.0
keras-vis 0.4.1

Though to be completely honest I'm still not sure as to what the issue is.

**Comment by HaiLongEmb** [comment]
> > @xuannianz
> > I retrain the model，get 0.000. Please help me, boss
> > Running network: 100% (1279 of 1279) |##########################################################################################| Elapsed Time: 0:02:15 Time: 0:02:15
> > Parsing annotations: 100% (1279 of 1279) |######################################################################################| Elapsed Time: 0:00:00 Time: 0:00:00
> > num_fp=0, num_tp=0
> > 3076 instances of class person with average precision: 0.0000
> > 937 instances of class person_1 with average precision: 0.0000
> > 4007 instances of class body with average precision: 0.0000
> 
> I had a similar issue while training with my own csv dataset.On someone's suggestion here I tried using the exact same versions of keras and tf mentioned below and it seemed to work:
> tensorflow 1.15.0
> Keras 2.2.5
> Keras-Applications 1.0.8
> Keras-Preprocessing 1.1.0
> keras-vis 0.4.1
> 
> Though to be completely honest I'm still not sure as to what the issue is.

I tried using the exact same versions of keras and tf mentioned below and it seemed not to work:
tensorflow 1.15.0
Keras 2.2.5
Keras-Applications 1.0.8
Keras-Preprocessing 1.1.0
keras-vis 0.4.1

What else can I do？

**Comment by balag59** [comment]
> > > @xuannianz
> > > I retrain the model，get 0.000. Please help me, boss
> > > Running network: 100% (1279 of 1279) |##########################################################################################| Elapsed Time: 0:02:15 Time: 0:02:15
> > > Parsing annotations: 100% (1279 of 1279) |######################################################################################| Elapsed Time: 0:00:00 Time: 0:00:00
> > > num_fp=0, num_tp=0
> > > 3076 instances of class person with average precision: 0.0000
> > > 937 instances of class person_1 with average precision: 0.0000
> > > 4007 instances of class body with average precision: 0.0000
> > 
> > 
> > I had a similar issue while training with my own csv dataset.On someone's suggestion here I tried using the exact same versions of keras and tf mentioned below and it seemed to work:
> > tensorflow 1.15.0
> > Keras 2.2.5
> > Keras-Applications 1.0.8
> > Keras-Preprocessing 1.1.0
> > keras-vis 0.4.1
> > Though to be completely honest I'm still not sure as to what the issue is.
> 
> I tried using the exact same versions of keras and tf mentioned below and it seemed not to work:
> tensorflow 1.15.0
> Keras 2.2.5
> Keras-Applications 1.0.8
> Keras-Preprocessing 1.1.0
> keras-vis 0.4.1
> 
> What else can I do？

I'm sorry but I have no idea so it's better you check with the authors of this code.

**Comment by olgarithmics** [comment]
i also encounter the same problem. Any suggestions?
