### ISSUE TITLE
How to test "custum csv model"?

### ISSUE THREAD

**Issue by JooHyungSon** [xuannianz/EfficientDet#32]
I understand that the "inference.py" file is a test file for PASCAL VOC data.

How can I use inference.py for my csv data?

Similarly, in /eval/commom.py it is difficult to evaluate csv data.

Thanks.

**Comment by xuannianz** [comment]
I've just updated the inference.py, it won't be specific to pascal any more.

**Comment by 2696120622** [comment]
> I understand that the "inference.py" file is a test file for PASCAL VOC data.
> 
> How can I use inference.py for my csv data?
> 
> Similarly, in /eval/commom.py it is difficult to evaluate csv data.
> 
> Thanks.

I have written a evaluate.ipynb using evaluate in eval.common.
You can write one by yourself.

**Comment by balag59** [comment]
> > I understand that the "inference.py" file is a test file for PASCAL VOC data.
> > How can I use inference.py for my csv data?
> > Similarly, in /eval/commom.py it is difficult to evaluate csv data.
> > Thanks.
> 
> I have written a evaluate.ipynb using evaluate in eval.common.
> You can write one by yourself.

Could you please share this in case you don't mind? Thanks!

**Comment by JooHyungSon** [comment]
> > I understand that the "inference.py" file is a test file for PASCAL VOC data.
> > How can I use inference.py for my csv data?
> > Similarly, in /eval/commom.py it is difficult to evaluate csv data.
> > Thanks.
> 
> I have written a evaluate.ipynb using evaluate in eval.common.
> You can write one by yourself.

please share your ipynb file? Thanks

**Comment by JooHyungSon** [comment]
> I've just updated the inference.py, it won't be specific to pascal any more.

Thanks you. I will test my data

**Comment by 2696120622** [comment]
> > > I understand that the "inference.py" file is a test file for PASCAL VOC data.
> > > How can I use inference.py for my csv data?
> > > Similarly, in /eval/commom.py it is difficult to evaluate csv data.
> > > Thanks.
> > 
> > 
> > I have written a evaluate.ipynb using evaluate in eval.common.
> > You can write one by yourself.
> 
> Could you please share this in case you don't mind? Thanks!

It will give a evaluation for your val data as the evaluation obtained during training.
However, it looks a little messy.
from model import efficientdet
import cv2
import os
import numpy as np
import time
from generators.csv_ import CSVGenerator
from eval.common import evaluate
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
phi = 0
weighted_bifpn = False
# weighted_bifpn = True

model_path = 'inference_checkpoints/inference_checkpoints_B0/freeze-backbone-false_1e-5/csv_05_0.3995_0.5901.h5'
# num_classes = generator.num_classes()
num_classes = 6
# classes = list(generator.classes.keys())
score_threshold = 0.01
# colors = [np.random.randint(0, 256, 3).tolist() for i in range(num_classes)]
model, prediction_model = efficientdet(phi=phi,
                    weighted_bifpn=weighted_bifpn,
                    num_classes=num_classes,
                    score_threshold=score_threshold)
prediction_model.load_weights(model_path, by_name=True)

validation_generator = CSVGenerator(
    'csv/val_annotations.csv',
    'csv/val_classes.csv',
    shuffle_groups=False,
    phi=phi
)

# run evaluation
average_precisions = evaluate(
    validation_generator,
    prediction_model,
    # iou_threshold=self.iou_threshold,
    # score_threshold=self.score_threshold,
    # max_detections=self.max_detections,
    visualize=False
)

verbose = 1
weighted_average = False
tensorboard = None
logs = {}

# compute per class average precision
total_instances = []  # 总实例
precisions = []  # 精确率
for label, (average_precision, num_annotations) in average_precisions.items():
    if verbose == 1:
        print('{:.0f} instances of class'.format(num_annotations),
                validation_generator.label_to_name(label), 'with average precision: {:.4f}'.format(average_precision))
    total_instances.append(num_annotations)
    precisions.append(average_precision)
if weighted_average:  # 如果使用加权平均，按各类实例数量进行加权平均
    mean_ap = sum([a * b for a, b in zip(total_instances, precisions)]) / sum(total_instances)
else:
    mean_ap = sum(precisions) / sum(x > 0 for x in total_instances)  # 直接求平均

if tensorboard is not None and tensorboard.writer is not None:
    import tensorflow as tf
    summary = tf.Summary()
    summary_value = summary.value.add()
    summary_value.simple_value = mean_ap
    summary_value.tag = "mAP"
    tensorboard.writer.add_summary(summary, epoch)

logs['mAP'] = mean_ap

if verbose == 1:
    print('mAP: {:.4f}'.format(mean_ap))

**Comment by balag59** [comment]
> > > > I understand that the "inference.py" file is a test file for PASCAL VOC data.
> > > > How can I use inference.py for my csv data?
> > > > Similarly, in /eval/commom.py it is difficult to evaluate csv data.
> > > > Thanks.
> > > 
> > > 
> > > I have written a evaluate.ipynb using evaluate in eval.common.
> > > You can write one by yourself.
> > 
> > 
> > Could you please share this in case you don't mind? Thanks!
> 
> It will give a evaluation for your val data as the evaluation obtained during training.
> However, it looks a little messy.
> from model import efficientdet
> import cv2
> import os
> import numpy as np
> import time
> from generators.csv_ import CSVGenerator
> from eval.common import evaluate
> os.environ['CUDA_VISIBLE_DEVICES'] = '0'
> phi = 0
> weighted_bifpn = False
> 
> # weighted_bifpn = True
> model_path = 'inference_checkpoints/inference_checkpoints_B0/freeze-backbone-false_1e-5/csv_05_0.3995_0.5901.h5'
> 
> # num_classes = generator.num_classes()
> num_classes = 6
> 
> # classes = list(generator.classes.keys())
> score_threshold = 0.01
> 
> # colors = [np.random.randint(0, 256, 3).tolist() for i in range(num_classes)]
> model, prediction_model = efficientdet(phi=phi,
> weighted_bifpn=weighted_bifpn,
> num_classes=num_classes,
> score_threshold=score_threshold)
> prediction_model.load_weights(model_path, by_name=True)
> 
> validation_generator = CSVGenerator(
> 'csv/val_annotations.csv',
> 'csv/val_classes.csv',
> shuffle_groups=False,
> phi=phi
> )
> 
> # run evaluation
> average_precisions = evaluate(
> validation_generator,
> prediction_model,
> # iou_threshold=self.iou_threshold,
> # score_threshold=self.score_threshold,
> # max_detections=self.max_detections,
> visualize=False
> )
> 
> verbose = 1
> weighted_average = False
> tensorboard = None
> logs = {}
> 
> # compute per class average precision
> total_instances = [] # 总实例
> precisions = [] # 精确率
> for label, (average_precision, num_annotations) in average_precisions.items():
> if verbose == 1:
> print('{:.0f} instances of class'.format(num_annotations),
> validation_generator.label_to_name(label), 'with average precision: {:.4f}'.format(average_precision))
> total_instances.append(num_annotations)
> precisions.append(average_precision)
> if weighted_average: # 如果使用加权平均，按各类实例数量进行加权平均
> mean_ap = sum([a * b for a, b in zip(total_instances, precisions)]) / sum(total_instances)
> else:
> mean_ap = sum(precisions) / sum(x > 0 for x in total_instances) # 直接求平均
> 
> if tensorboard is not None and tensorboard.writer is not None:
> import tensorflow as tf
> summary = tf.Summary()
> summary_value = summary.value.add()
> summary_value.simple_value = mean_ap
> summary_value.tag = "mAP"
> tensorboard.writer.add_summary(summary, epoch)
> 
> logs['mAP'] = mean_ap
> 
> if verbose == 1:
> print('mAP: {:.4f}'.format(mean_ap))

Thanks a ton this is great!

**Comment by 2696120622** [comment]
Those line with large word are notes starting with #.  I don't know how to display these code in python style.

**Comment by balag59** [comment]
> Those line with large word are notes starting with #. I don't know how to display these code in python style.

Yup I got that thanks!

**Comment by 2696120622** [comment]
The following may be normal.
`
from model import efficientdet
import cv2
import os
import numpy as np
import time

from generators.csv_ import CSVGenerator
from eval.common import evaluate

os.environ['CUDA_VISIBLE_DEVICES'] = '0'
phi = 0
weighted_bifpn = False
# weighted_bifpn = True

model_path = 'inference_checkpoints/inference_checkpoints_B0/freeze-backbone-false_1e-5/csv_05_0.3995_0.5901.h5'
# num_classes = generator.num_classes()
num_classes = 6
# classes = list(generator.classes.keys())
score_threshold = 0.01
# colors = [np.random.randint(0, 256, 3).tolist() for i in range(num_classes)]

model, prediction_model = efficientdet(phi=phi,
                    weighted_bifpn=weighted_bifpn,
                    num_classes=num_classes,
                    score_threshold=score_threshold)

prediction_model.load_weights(model_path, by_name=True)

validation_generator = CSVGenerator(
    'csv/val_annotations.csv',
    'csv/val_classes.csv',
    shuffle_groups=False,
    phi=phi
)
# run evaluation
average_precisions = evaluate(
    validation_generator,
    prediction_model,
    # iou_threshold=self.iou_threshold,
    # score_threshold=self.score_threshold,
    # max_detections=self.max_detections,
    visualize=False
)

verbose = 1
weighted_average = False
tensorboard = None
logs = {}

# compute per class average precision
total_instances = []  # 总实例
precisions = []  # 精确率
for label, (average_precision, num_annotations) in average_precisions.items():
    if verbose == 1:
        print('{:.0f} instances of class'.format(num_annotations),
                validation_generator.label_to_name(label), 'with average precision: {:.4f}'.format(average_precision))
    total_instances.append(num_annotations)
    precisions.append(average_precision)
if weighted_average:  # 如果使用加权平均，按各类实例数量进行加权平均
    mean_ap = sum([a * b for a, b in zip(total_instances, precisions)]) / sum(total_instances)
else:
    mean_ap = sum(precisions) / sum(x > 0 for x in total_instances)  # 直接求平均

if tensorboard is not None and tensorboard.writer is not None:
    import tensorflow as tf
    summary = tf.Summary()
    summary_value = summary.value.add()
    summary_value.simple_value = mean_ap
    summary_value.tag = "mAP"
    tensorboard.writer.add_summary(summary, epoch)

logs['mAP'] = mean_ap

if verbose == 1:
    print('mAP: {:.4f}'.format(mean_ap))
`

**Comment by JooHyungSon** [comment]
> Those line with large word are notes starting with #. I don't know how to display these code in python style.

Can you upload your code to GitHub?
