### ISSUE TITLE
A puzzle about features returned by EfficientNet in efficientnet.py

### ISSUE THREAD

**Issue by 2696120622** [xuannianz/EfficientDet#33]
According to function EfficientNet defined in efficientnet.py, the features returned by it has five elements corresponding to five different stages of efficientnet respectively. Why is the first element  not the output of the first convolution operation followed by BN and swish?

**Comment by xuannianz** [comment]
I have no idea. It's consistent with the official implementation of EfficientNet, you may ask them.

**Comment by 2696120622** [comment]
> I have no idea. It's consistent with the official implementation of EfficientNet, you may ask them.

Ok. Thanks!
