### ISSUE TITLE
How to change h5 model to pb models?

### ISSUE THREAD

**Issue by fuweifu-vtoo** [xuannianz/EfficientDet#37]
Thanks for your work
One question is, how do I convert the h5 model into a pb model?
Can you provide a script to do such a job?I encountered a problem while doing in shape of weight

**Comment by xuannianz** [comment]
Hi, @fuweifu-vtoo.
One way is to convert h5 to .index, .data and checkpoint firstly by using `model.save_weights('xxx', save_format='tf')`, then convert these separated files into a pb file.
You can also search on google, there are lots of better answers.

**Comment by can2049** [comment]
hi, @fuweifu-vtoo  have you solved this problem?
