### ISSUE TITLE
error when loading model with tf.keras.models.load_model

### ISSUE THREAD

**Issue by 2696120622** [xuannianz/EfficientDet#49]
When loading model with this, I get the following erro.
keras.models.load_model(filepath='.h5',custom_objects=custom_objects)  
with  
custom_objects = {  
    'BatchNormalization': layers_new.BatchNormalization,   
    'swish'            : efficientnet.get_swish(),  
    'FixedDropout'     :  
 efficientnet.get_dropout(backend=keras.backend,layers=keras.layers,models=keras.models,utils=keras.utils),  
    'wBiFPNAdd'        : layers_new.wBiFPNAdd,  
}   

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-f5b5e441bd42> in <module>()
      1 keras.models.load_model(filepath='ckpts/ckpts_B1/freeze-backbone-false-1e-6-bs2-rotate-flip-new/csv_06_0.6883_0.7987.h5',
----> 2                                                           custom_objects=custom_objects)

9 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/save.py in load_model(filepath, custom_objects, compile)
    141   if (h5py is not None and (
    142       isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):
--> 143     return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
    144 
    145   if isinstance(filepath, six.string_types):

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/hdf5_format.py in load_model_from_hdf5(filepath, custom_objects, compile)
    160     model_config = json.loads(model_config.decode('utf-8'))
    161     model = model_config_lib.model_from_config(model_config,
--> 162                                                custom_objects=custom_objects)
    163 
    164     # set weights

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/saving/model_config.py in model_from_config(config, custom_objects)
     53                     '`Sequential.from_config(config)`?')
     54   from tensorflow.python.keras.layers import deserialize  # pylint: disable=g-import-not-at-top
---> 55   return deserialize(config, custom_objects=custom_objects)
     56 
     57 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/serialization.py in deserialize(config, custom_objects)
    103       module_objects=globs,
    104       custom_objects=custom_objects,
--> 105       printable_module_name='layer')

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    189             custom_objects=dict(
    190                 list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 191                 list(custom_objects.items())))
    192       with CustomObjectScope(custom_objects):
    193         return cls.from_config(cls_config)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py in from_config(cls, config, custom_objects)
   1069     # First, we create all layers and enqueue nodes to be processed
   1070     for layer_data in config['layers']:
-> 1071       process_layer(layer_data)
   1072     # Then we process nodes in order of layer depth.
   1073     # Nodes that cannot yet be processed (if the inbound node

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/network.py in process_layer(layer_data)
   1053       from tensorflow.python.keras.layers import deserialize as deserialize_layer  # pylint: disable=g-import-not-at-top
   1054 
-> 1055       layer = deserialize_layer(layer_data, custom_objects=custom_objects)
   1056       created_layers[layer_name] = layer
   1057 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/layers/serialization.py in deserialize(config, custom_objects)
    103       module_objects=globs,
    104       custom_objects=custom_objects,
--> 105       printable_module_name='layer')

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    191                 list(custom_objects.items())))
    192       with CustomObjectScope(custom_objects):
--> 193         return cls.from_config(cls_config)
    194     else:
    195       # Then `cls` may be a function returning a class.

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py in from_config(cls, config)
    599         A layer instance.
    600     """
--> 601     return cls(**config)
    602 
    603   def compute_output_shape(self, input_shape):

TypeError: type object argument after ** must be a mapping, not NoneType                        

How to fix this error or load model with tf.keras.models.load_model successfully?

**Comment by 2696120622** [comment]
@xuannianz
When loading model without passing ----weighted-bifpn using tf.keras.models.load_model, I can load the model successfully.
So, I think there are some improvements in  layers_new.wBiFPNAdd for supporting  tf.keras.models.load_model.

**Comment by xuannianz** [comment]
Yes, we should add name for the weights of wBiFPNAdd layers, check out the latest code.

**Comment by 2696120622** [comment]
> Yes, we should add name for the weights of wBiFPNAdd layers, check out the latest code.

Thanks. I have added name for the weights of wBiFPN layers by myself as the following:
        self.w = self.add_weight(name='wbifpnadd',  
                                 shape=(num_in,),  
                                 initializer=keras.initializers.constant(1 / num_in),  
                                 trainable=True,  
                                 dtype=tf.float32)  
is it OK?

If it is OK, however, when loading model with tf.keras.models.load_model, I still get the same error.
The following are code of mine and error.

custom_objects = {
    'BatchNormalization': layers_new.BatchNormalization,
    'swish'            : efficientnet.get_swish(),
    'FixedDropout'     : efficientnet.get_dropout(backend=keras.backend,layers=keras.layers,models=keras.models,utils=keras.utils),
    'wBiFPNAdd'        : layers_new.wBiFPNAdd,
    'PriorProbability' : initializers.PriorProbability,
    'RegressBoxes'     : layers_new.RegressBoxes,
    'FilterDetections' : layers_new.FilterDetections,
    'ClipBoxes'        : layers_new.ClipBoxes,
    '_smooth_l1'       : losses.smooth_l1(),
    '_focal'           : losses.focal(),
}

TypeError                                 Traceback (most recent call last)
<ipython-input-22-0701e935a782> in <module>()
      1 
----> 2 lmodel = keras.models.load_model('ckpts/ckpts_B1/freeze-backbone-true_1e-3/csv_01_2.6197_1.8986.h5',custom_objects=custom_objects)

9 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py in from_config(cls, config)
    599         A layer instance.
    600     """
--> 601     return cls(**config)
    602 
    603   def compute_output_shape(self, input_shape):

TypeError: type object argument after ** must be a mapping, not NoneType

Can you give some idea on how to fix this error or how to load the model with tf.keras.models.load_model?

**Comment by 2696120622** [comment]
> Yes, we should add name for the weights of wBiFPNAdd layers, check out the latest code.

I copied your latest code layers.py and model.py  and retrain the model.
when loading the trained model with tf.keras.models.load_model, I still get the same error.
The following are code of mine and error.

import layers as layers_new
import initializers
import losses
import efficientnet
import tensorflow as tf
custom_objects = {
    'BatchNormalization': layers_new.BatchNormalization,
    'swish'            : efficientnet.get_swish(),
    'FixedDropout'     : efficientnet.get_dropout(backend=keras.backend,layers=keras.layers,models=keras.models,utils=keras.utils),
    'wBiFPNAdd'        : layers_new.wBiFPNAdd,
    'PriorProbability' : initializers.PriorProbability,
    'RegressBoxes'     : layers_new.RegressBoxes,
    'FilterDetections' : layers_new.FilterDetections,
    'ClipBoxes'        : layers_new.ClipBoxes,
    '_smooth_l1'       : losses.smooth_l1(),
    '_focal'           : losses.focal(),
}

lmodel = keras.models.load_model('ckpts/ckpts_B1/freeze-backbone-true_1e-3/csv_01_2.5759_1.9022.h5',custom_objects=custom_objects)

TypeError                                 Traceback (most recent call last)
<ipython-input-17-312723206bc9> in <module>()
      1 
----> 2 lmodel = keras.models.load_model('ckpts/ckpts_B1/freeze-backbone-true_1e-3/csv_01_2.5759_1.9022.h5',custom_objects=custom_objects)

9 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py in from_config(cls, config)
    599         A layer instance.
    600     """
--> 601     return cls(**config)
    602 
    603   def compute_output_shape(self, input_shape):

TypeError: type object argument after ** must be a mapping, not NoneType

I think there are still some improvements in layers_new.wBiFPNAdd for supporting tf.keras.models.load_model. Because the error appear when adding 'wBiFPNAdd'        : layers_new.wBiFPNAdd into custom_objects.

**Comment by xuannianz** [comment]
No, it works fine in my local env. Was your model weights trained before #27 ?

**Comment by 2696120622** [comment]
Thanks. I forget the 'return config' in get_config(self). I will try again.

Could you share your code on how to load model with tf.keras.models.load method? I just have some puzzle on how to set custom_objects.

**Comment by 2696120622** [comment]
Now I can load the model with tf.keras.models.load as follows.

import tensorflow as tf
from tensorflow import keras  
import layers as layers_new  
import initializers  
import losses  
import efficientnet  

custom_objects = {
    'BatchNormalization': layers_new.BatchNormalization,
    'swish'            : efficientnet.get_swish(backend=keras.backend,layers=keras.layers,models=keras.models,utils=keras.utils),
    'FixedDropout'     : efficientnet.get_dropout(backend=keras.backend,layers=keras.layers,models=keras.models,utils=keras.utils),
    'wBiFPNAdd'        : layers_new.wBiFPNAdd,  
    'PriorProbability' : initializers.PriorProbability,  
    'RegressBoxes'     : layers_new.RegressBoxes,  
    'FilterDetections' : layers_new.FilterDetections,  
    'ClipBoxes'        : layers_new.ClipBoxes,  
    '_smooth_l1'       : losses.smooth_l1(),  
    '_focal'           : losses.focal(),  
}  
lmodel = keras.models.load_model('inference_ckpts/ckpts_B1/freeze-backbone-true_1e- 
 3/csv_01_1.0837_1.0793.h5', custom_objects=custom_objects)  

I also convert the model to tflite as follows.  
  
converter = tf.lite.TFLiteConverter.from_keras_model_file('ckpts/ckpts_B1/freeze-backbone-true_1e- 
3/csv_01_1.0837_1.0793.h5',custom_objects=custom_objects,)  
tflite_model = converter.convert()
open("tflite/csv_01_1.0837_1.0793.tflite", "wb").write(tflite_model)  

I don't know if the custom_objects defined above are reasonalbe, but it works well for tf.keras.models.load and  tf.lite.TFLiteConverter.from_keras_model_file.

**Comment by 2696120622** [comment]
However, if I save the prediction_model firstly.
`
prediction_model.save('inference_ckpts/ckpts_B1/freeze-backbone-true_1e-3/csv_01_1.0837_1.0793.h5')
`
Then, when converting the model to tflite,I get another error.

`
converter = tf.lite.TFLiteConverter.from_keras_model_file('inference_ckpts/ckpts_B1/freeze-backbone-true_1e-3/csv_01_1.0837_1.0793.h5',custom_objects=custom_objects,)  
tflite_model = converter.convert()  
`

ValueError                                Traceback (most recent call last)
<ipython-input-37-c548bab089a8> in <module>()
----> 1 tflite_model = converter.convert()

/usr/local/lib/python3.6/dist-packages/tensorflow_core/lite/python/lite.py in convert(self)
    894               "None is only supported in the 1st dimension. Tensor '{0}' has "
    895               "invalid shape '{1}'.".format(
--> 896                   _get_tensor_name(tensor), shape_list))
    897         elif shape_list and shape_list[0] is None:
    898           self._set_batch_size(batch_size=1)

ValueError: None is only supported in the 1st dimension. Tensor 'input_4' has invalid shape '[1, None, 4]'.

How should I set the tensor 'input_4' with a valid shape?
