### ISSUE TITLE
evaluate bug：Need to set freeze_bn to true when testing

### ISSUE THREAD

**Issue by jzq6520** [xuannianz/EfficientDet#50]
eval/commont.py `model, prediction_model = efficientdet(phi=phi, num_classes=num_classes, weighted_bifpn=weighted_bifpn)`  `freeze_bn` default equal  False，**we need set `freeze_bn = True` when test model**。 
Otherwise mAP is only  about 0.01

**Comment by 2696120622** [comment]
I do not set freeze_bn = True, but mAP is not about 0.01 and normal.

**Comment by jzq6520** [comment]
@2696120622 Maybe it is my keras version problem, I used keras=2.2.4, tf=1.4.0。when test bn training problem
