### ISSUE TITLE
The difference of tensorflow.keras.model.Model() and keras.model.Model()

### ISSUE THREAD

**Issue by GithubAbner** [xuannianz/EfficientDet#56]
Thank you very much for your contribution and sharing.
There is a question puzzled me. Why does tensorflow.keras.model.Model() work in model.py(build_regress_head() and build_class_head()), not keras.model.Model()? Is there any difference between them? 
Looking forward to your answer. Thank you very much.

**Comment by PieroCV** [comment]
This repo is working with original keras API. But it is possible to work with tf.keras, in my case, I'm working with tensorflow 2.0, and the changes are minimal.

**Comment by GithubAbner** [comment]
> This repo is working with original keras API. But it is possible to work with tf.keras, in my case, I'm working with tensorflow 2.0, and the changes are minimal.

But in this repo, the tf.keras was used and it works well. I try to replace the tf.keras with keras, error occured, and I cannot fix the bug.

**Comment by 2696120622** [comment]
> This repo is working with original keras API. But it is possible to work with tf.keras, in my case, I'm working with tensorflow 2.0, and the changes are minimal.

Could you share your tf 2.0 code? How much have you changed?

**Comment by 2696120622** [comment]
> This repo is working with original keras API. But it is possible to work with tf.keras, in my case, I'm working with tensorflow 2.0, and the changes are minimal.

@PieroCV Can you convert the model trained with TF 2 to tflite and use the tflite model for inference?

**Comment by 2696120622** [comment]
> This repo is working with original keras API. But it is possible to work with tf.keras, in my case, I'm working with tensorflow 2.0, and the changes are minimal.

 I'm working with tensorflow 2.0. I got an error as follows. Dou you know how to resolve it?
`Traceback (most recent call last):
  File "train.py", line 405, in <module>
    main()
  File "train.py", line 339, in main
    anchor_extend=args.anchor_extend)  # 构建模型和预测模型 # 191216
  File "/content/drive/My Drive/EfficientDet-region_anchor_opt_mbconv-head_tf2/model.py", line 527, in efficientdet
    features = backbone_cls(input_tensor=image_input, freeze_bn=freeze_bn)  # 获取特征
  File "/content/drive/My Drive/EfficientDet-region_anchor_opt_mbconv-head_tf2/utils/__init__.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/content/drive/My Drive/EfficientDet-region_anchor_opt_mbconv-head_tf2/efficientnet.py", line 456, in EfficientNetB0
    **kwargs)
  File "/content/drive/My Drive/EfficientDet-region_anchor_opt_mbconv-head_tf2/efficientnet.py", line 395, in EfficientNet
    x = BatchNormalization(freeze=freeze_bn, axis=bn_axis, name='stem_bn')(x)  # BN
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 842, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

    /content/drive/My Drive/EfficientDet-region_anchor_opt_mbconv-head_tf2/layers.py:22 call  *
        if not training:
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/operators/control_flow.py:893 if_stmt
        basic_symbol_names, composite_symbol_names)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/operators/control_flow.py:931 tf_if_stmt
        error_checking_orelse)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py:507 new_func
        return func(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py:1174 cond
        return cond_v2.cond_v2(pred, true_fn, false_fn, name)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/cond_v2.py:93 cond_v2
        verify_captures(_COND, [true_graph, false_graph])
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/cond_v2.py:768 verify_captures
        b1name=branch_names[i]))

    ValueError: Tensor stem_bn_trainable:0 in true_fn is accessed from false_fn.`

**Comment by KUASWoodyLIN** [comment]
@2696120622 

For TensorFlow2.0, 
You just change all 
```python
 x = BatchNormalization(freeze=freeze_bn, ...)(x)
```
into 
```python
x = layers.BatchNormalization(trainable=not freeze_bn, ....)(x)
```

**Comment by 2696120622** [comment]
@KUASWoodyLIN 
Thanks a lot.
Can you share the reason for this change?
Should I also change all
`f2 = BatchNormalization(freeze=freeze_bn, name='{}_bn'.format(name))`
into
`f2 = BatchNormalization(trainable=not freeze_bn, name='{}_bn'.format(name))`

**Comment by KUASWoodyLIN** [comment]
@2696120622 

Custom BatchNormalization add freeze parameters to freeze the weights, 
maybe because Keras BatchNormalization can't do it. 
https://github.com/keras-team/keras/blob/master/keras/layers/normalization.py#L16

But for tensorflow.keras BatchNormalization weights can be freeze by trainable.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/normalization_v2.py#L208

**Comment by KUASWoodyLIN** [comment]
@2696120622 

If you want to run on TensorFlow 2.0
Check this out, I already modify it.
https://github.com/KUASWoodyLIN/EfficientDet/tree/tf2.0

**Comment by 2696120622** [comment]
@KUASWoodyLIN 
Thanks.
I will have a try. Can you convert the model trained with tf 2.0 to tflite successfully?

**Comment by KUASWoodyLIN** [comment]
@2696120622 
Sorry I haven't had that experience

**Comment by 2696120622** [comment]
@KUASWoodyLIN 
OK.I will do that.

**Comment by 2696120622** [comment]
@KUASWoodyLIN
I have read your code.
(1) In efficientnet.py, are these two lines python comments?
`import tensorflow as tf
tf.keras.layers.BatchNormalization`

(2) In
`x = layers.BatchNormalization(trainable=not freeze_bn, ....)(x)`,
which one does layers refer to? tf.keras.layers or layers.py defined in your repository KUASWoodyLIN/EfficientDet?
(3) Does
`    def on_train_begin(self, logs=None):
        path = os.path.join(self.log_dir, 'validation')
        self.writer = tf.summary.create_file_writer(path)`
must be included in eval/pascal.py?

**Comment by KUASWoodyLIN** [comment]
@2696120622 

(1) those two line I forget to remove.

(2) tf.keras.layers

(3) It because `eval/pascal.py` have some error in tf2, so need to add them

**Comment by 2696120622** [comment]
> @2696120622
> 
> (1) those two line I forget to remove.
> 
> (2) tf.keras.layers
> 
> (3) It because `eval/pascal.py` have some error in tf2, so need to add them

@KUASWoodyLIN 
Why my training stop with the following outputs.
`{'dataset_type': 'csv', 'snapshot': 'imagenet', 'freeze_backbone': True, 'freeze_bn': False, 'weighted_bifpn': True, 'batch_size': 4, 'phi': 0, 'gpu': None, 'num_gpus': 0, 'multi_gpu_force': False, 'epochs': 2, 'steps': 10000, 'lr': 0.001, 'snapshot_path': 'ckpts/ckpts_B1_image-size-640/mbconv_head_anchor-extend_1e-3', 'tensorboard_dir': 'logs/logs_B1_image-size-640/mbconv_head_anchor-extend_1e-3', 'snapshots': True, 'evaluation': True, 'random_transform': False, 'compute_val_loss': True, 'config': 'config/config_640_anchor_extend_mbconv_head.ini', 'rotate_flip_new': True, 'mbconv_head': True, 'head_mbconv_se': True, 'anchor_extend': True, 'anchor_extend_deconv': False, 'multiprocessing': False, 'workers': 1, 'max_queue_size': 10, 'annotations_path': 'csv/train_annotations.csv', 'classes_path': 'csv/train_classes.csv', 'val_annotations_path': 'csv/val_annotations.csv'}
args.config config/config_640_anchor_extend_mbconv_head.ini
config['image_bifpn_head_params'].items() ItemsView(<Section: image_bifpn_head_params>)
config['head_mbconv_params'].items() ItemsView(<Section: head_mbconv_params>)
image_bifpn_head_params: {'image_sizes': [640, 640, 768, 896, 1024, 1280, 1408], 'w_bifpns': [88, 88, 112, 160, 224, 288, 384], 'd_bifpns': [1, 1, 4, 5, 6, 7, 8], 'w_heads': [88, 88, 112, 160, 224, 288, 384], 'd_heads': [4, 4, 3, 4, 4, 4, 5]}
anchor_params:  [32, 64, 128, 256, 512] [8, 16, 32, 64, 128] [0.383 0.578 1.    1.731 2.613] [0.534 0.669 0.872]
anchor_params:  [32, 64, 128, 256, 512] [8, 16, 32, 64, 128] [0.383 0.578 1.    1.731 2.613] [0.534 0.669 0.872]
2020-02-14 10:37:48.085609: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-02-14 10:37:48.097732: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2300000000 Hz
2020-02-14 10:37:48.097959: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x27f9640 executing computations on platform Host. Devices:
2020-02-14 10:37:48.097996: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:`batch_size` is no longer needed in the `TensorBoard` Callback and will be ignored in TensorFlow 2.0.
Epoch 1/2
^C`

**Comment by KUASWoodyLIN** [comment]
@2696120622 
I'm not sure what cause this error, 
Is you running fine without "^C"

**Comment by 2696120622** [comment]
@KUASWoodyLIN 
Code can not continue running, after outputting " 
 Epoch 1/2 ^C".

**Comment by 2696120622** [comment]
@KUASWoodyLIN 
I am running fine using tf 2.1.
However, running stop with "^C" as the following outputs when using tf 2.0.
