### ISSUE TITLE
how to inference a image with pretrained weight?

### ISSUE THREAD

**Issue by ZOUYIyi** [xuannianz/EfficientDet#59]
in the link of download pretrained weight,there are lots of .h5 files,so I just down load one and fix the path of it in the inference.py，but nothing is detected in the image , I think maybe I have a wrong weight file ,but I dont know how to make it works

**Comment by aisandovalm** [comment]
> in the link of download pretrained weight,there are lots of .h5 files,so I just down load one and fix the path of it in the inference.py，but nothing is detected in the image , I think maybe I have a wrong weight file ,but I dont know how to make it works

Same here, I've tested B0 to B6 loading the corresponding pre-trained weights, but I'm only getting 0 predictions.

**Comment by aisandovalm** [comment]
> > in the link of download pretrained weight,there are lots of .h5 files,so I just down load one and fix the path of it in the inference.py，but nothing is detected in the image , I think maybe I have a wrong weight file ,but I dont know how to make it works
> 
> Same here, I've tested B0 to B6 loading the corresponding pre-trained weights, but I'm only getting 0 predictions.

I think we are not getting any predictions because the weights available in the download link only include the layers from the backbone net (EfficientNet). So, in order to get predictions, we have to train the BiFPN network first (freezing the EfficientNet layers).

**Comment by ZOUYIyi** [comment]
> in the link of download pretrained weight,there are lots of .h5 files,so I just down load one and fix the path of it in the inference.py，but nothing is detected in the image , I think maybe I have a wrong weight file ,but I dont know how to make it works
> 
> Same here, I've tested B0 to B6 loading the corresponding pre-trained weights, but I'm only getting 0 predictions.
> 
> I think we are not getting any predictions because the weights available in the download link only include the layers from the backbone net (EfficientNet). So, in order to get predictions, we have to train the BiFPN network first (freezing the EfficientNet layers).



> in the link of download pretrained weight,there are lots of .h5 files,so I just down load one and fix the path of it in the inference.py，but nothing is detected in the image , I think maybe I have a wrong weight file ,but I dont know how to make it works
> 
> Same here, I've tested B0 to B6 loading the corresponding pre-trained weights, but I'm only getting 0 predictions.
> 
> I think we are not getting any predictions because the weights available in the download link only include the layers from the backbone net (EfficientNet). So, in order to get predictions, we have to train the BiFPN network first (freezing the EfficientNet layers).

In the Evaluate part ,there is a table contains two number 0.8029  0.7892 ,from which we can down load weights ,the name of two weight files are  just like the right one ,I have already fixed the phi in the code ,but I still cann't get right predictions ,you can try it with the weights, tell me what happens.

**Comment by xuannianz** [comment]
Hi @ZOUYIyi ,did you run inference.py? Note that you just need to replace the weights path and image path there when test with the "0.8029" weights.
And if you test with "0.7892" weights, you also need to set `phi=0, weighted_bifpn=True`.

**Comment by ZOUYIyi** [comment]
> Hi @ZOUYIyi ,did you run inference.py? Note that you just need to replace the weights path and image path there when test with the "0.8029" weights.
> And if you test with "0.7892" weights, you also need to set phi=0, weighted_bifpn=True.

thank you! it works! still one more question..... I use tensorflow 1.13.1 and keras2.2.5，and it raise a error:
File "C:\Users\WIN10\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\keras\engine\base_layer_utils.py", line 127,
in <lambda>
 shape, dtype=dtype, partition_info=None)
TypeError: __call__() got an unexpected keyword argument 'partition_info' 

I know it is because of the unmatch of tensorflow and keras,but how can I fix it in the code ,instead of updating my tensorflow ?   right now ,I just fix the keras file in the error message ,I dont know if it is ok to do that .
