### ISSUE TITLE
一堆错误，请问下python什么版本

### ISSUE THREAD

**Issue by tsangsea** [xuannianz/EfficientDet#63]
跑不起来，请问下python什么版本，报如下错误：
 P6_td = wBiFPNAdd(name='w_bi_fpn_add' if id == 0 else f'w_bi_fpn_add_{8 * id}')([P7_U, P6_in])
│SyntaxError: invalid syntax

**Comment by 2696120622** [comment]
python 3.6.5 or 3.6.9 works well

**Comment by bill2239** [comment]
how about tensorflow's version?

**Comment by 2696120622** [comment]
tf 1.15.0
keras  2.2.5
