### ISSUE TITLE
trained model on MSCOCO

### ISSUE THREAD

**Issue by ma-siddiqui** [xuannianz/EfficientDet#66]
Hi,

Can you please share your trained model on MSCOCO?

Thanks,
Ajmal

**Comment by xuannianz** [comment]
Sorry, no @ma-siddiqui. I trained Efficient-D0 once on coco but did not get a mAP score close to what the paper shows.

**Comment by sliawatimena** [comment]
I try to run with:
```
$ python3 train.py --snapshot imagenet --phi 0 --gpu 0 --random-transform --compute-val-loss --freeze-
backbone --batch-size 32 --steps 1000 coco

usage: train.py coco [-h] coco_path
train.py coco: error: the following arguments are required: coco_path
```


I already set
coco_path='/home/suryadi/d/learn/learn/coco'
in that directory I already have train2017, test2017 and val2017

How to give the correct command to train with coco?

Thank you very much .

**Comment by tensorflowt** [comment]
> Sorry, no @ma-siddiqui. I trained Efficient-D0 once on coco but did not get a mAP score close to what the paper shows.
Hello! What is the mAP of the Efficient-D0 model based on the COCO data set that you trained yourself?

**Comment by xuannianz** [comment]
Hi @tensorflowt , it's 0.296. I'm going to improve it recently.

**Comment by tensorflowt** [comment]
That's good news. I hope to hear from you next month.
Best wishes！

**Comment by km23630** [comment]
@tensorflowt 

https://1drv.ms/u/s!Akh0ty3UfIgE-Z9AHKdq1lMTLnf0Hw?e=ioftEp
this is my coco trained model.

**Comment by ma-siddiqui** [comment]
> @tensorflowt
> 
> https://1drv.ms/u/s!Akh0ty3UfIgE-Z9AHKdq1lMTLnf0Hw?e=ioftEp
> this is my coco trained model.

Hi, this model is trained on D7 or D0? Also you have achieved the same results claimed in the paper?

**Comment by km23630** [comment]
> > @tensorflowt
> > https://1drv.ms/u/s!Akh0ty3UfIgE-Z9AHKdq1lMTLnf0Hw?e=ioftEp
> > this is my coco trained model.
> 
> Hi, this model is trained on D7 or D0? Also you have achieved the same results claimed in the paper?

1. maybe D1
2. no :(

**Comment by ma-siddiqui** [comment]
Hi, this model (  https://1drv.ms/u/s!Akh0ty3UfIgE-Z9AHKdq1lMTLnf0Hw?e=ioftEp) is trained on D7 or D0? Also you have achieved the same results claimed in the paper?
