### ISSUE TITLE
No. Trainable variables mismatch with the number in the paper

### ISSUE THREAD

**Issue by MahmoudTamam** [xuannianz/EfficientDet#67]
Hello,

I found that when i print the model summary of EfficientDet-D0 that Number of Parameters is: 4.2
![image](https://user-images.githubusercontent.com/12560992/73400187-4cb98680-42f1-11ea-944c-7cd5fd42f61b.png)

While in the paper EfficientDet-D0 Number of Parameters is : **3.9M**
from:  Table2 

![image](https://user-images.githubusercontent.com/12560992/73399694-627a7c00-42f0-11ea-9b89-7f7203b8c1fb.png)

I used input size with 512x512x3 as stated in paper in Table 1:
![image](https://user-images.githubusercontent.com/12560992/73400256-71156300-42f1-11ea-858e-7d9c1eb18126.png)

Also, Thanks for the awesome implementation.

**Comment by xuannianz** [comment]
Thanks for pointing this out, let's wait for the official implementation. #15
