### ISSUE TITLE
model input/output is different predict_on_batch input/output

### ISSUE THREAD

**Issue by km23630** [xuannianz/EfficientDet#69]
I want to accelerate inference using TensorRT.
when I convert  keras model to TensorRT,  output is different from "prediction_model.predict_on_batch"' output

model input : 'input_1'
model_output : 'regression/concat', 'classification/concat'

predict_on_batch input : image_batch
predict_on_batch output : boxes, scores, labels

Why does this difference occur?

Please tell me the code for anchors_batch in "prediction_model.predict_on_batch" 
and the code for converting "regression / concat" and "classification / concat" 
to boxes, scores, labels.

thanks.

**Comment by SuJiaKuan** [comment]
You may get outputs from wrong model:

```python
model, prediction_model = efficientdet(phi=phi,
                                                                                   weighted_bifpn=weighted_bifpn,
                                                                                   num_classes=num_classes,
                                                                                   score_threshold=score_threshold)
output_names = [t.op.name for t in prediction_model.outputs]
```

As shown above code, you need to get outputs from `prediction_model` instead of `model`.
