### ISSUE TITLE
About the eval of pretrained weights

### ISSUE THREAD

**Issue by silence0628** [xuannianz/EfficientDet#7]
I used your eval code,"python3 eval/common.py to evaluate by specifying model path there.",but error found,
ValueError: Layer #1 (named "stem_conv"), weight <tf.Variable 'stem_conv/kernel:0' shape=(3, 3, 3, 32) dtype=float32> has shape (3, 3, 3, 32), but the saved weight has shape (64, 3, 3, 3).

Can you tell me. what is weights(***.h5) you used in eval? Thank you!

**Comment by xuannianz** [comment]
Hi @silence0628 , I just uploaded two weights trained on PASCAL VOC.

**Comment by djaym7** [comment]
> Hi @silence0628 , I just uploaded two weights trained on PASCAL VOC.

What input resolution did you train the model on and which specific model did you upload weights of (EfficientDet_d0,d1.. ?)
