### ISSUE TITLE
inference error during predict_on_batch

### ISSUE THREAD

**Issue by edwardyangxin** [xuannianz/EfficientDet#70]
![image](https://user-images.githubusercontent.com/13101725/73727455-7567d300-476c-11ea-98ec-813590848df3.png)

environment is the same as the requirements.txt

code for loading model and test image:
![image](https://user-images.githubusercontent.com/13101725/73727632-d7283d00-476c-11ea-8679-e1c9caf298db.png)
![image](https://user-images.githubusercontent.com/13101725/73727672-ec04d080-476c-11ea-9542-cb301a67c6ad.png)

**Comment by edwardyangxin** [comment]
turns out my GPU MEM is not sufficient. so I close this issue

**Comment by rose-jinyang** [comment]
Hello
You met this issue but solved by adding this code at the start of script.

import tensorflow as tf
from tensorflow.compat.v1.keras.backend import set_session
config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True  # dynamically grow the memory used on the GPU
sess = tf.compat.v1.Session(config=config)
set_session(sess)

I hope that this will help you.
