### ISSUE TITLE
OOM when training EfficientDet-D3 step2 with single GPU

### ISSUE THREAD

**Issue by KaqiKaqi** [xuannianz/EfficientDet#71]
I tried to train EfficientDet-D3 step2 with batch-size=4 with single GPU, but could not succeed due to OOM. The GPU has 11178MiB memory. Have successfuly trained EfficientDet-D3 step2 with single GPU?

And it seems multi-gpu is not yet supported, do you have any plan to support multi gpu?

Thanks a lot.

**Comment by xuannianz** [comment]
Hi @KaqiKaqi, you could utilize multi_gpu_model to wrap your model.
`
from keras.utils import multi_gpu_model

model, prediction_model = efficientdet(args.phi, num_classes=num_classes,
                                           weighted_bifpn=args.weighted_bifpn,
                                           freeze_bn=args.freeze_bn)
model = multi_gpu_model(model)
`

**Comment by KaqiKaqi** [comment]
@xuannianz Thanks a lot.

**Comment by sliawatimena** [comment]
Is there any possibility to utilize computer (or notebook) DRAM RAM to expand GPU RAM? How to do that? Thank you.
