### ISSUE TITLE
When phi == 1, the size of the model is 78.4Mb, but the size in the paper is only 6.6Mb

### ISSUE THREAD

**Issue by yujun2019** [xuannianz/EfficientDet#8]

**Comment by florisdesmedt** [comment]
Is it possible you are comparing file size with the number of parameters? Although there is a difference. With phi=1 I get 7.6M parameters (with the 80 COCO classes)

**Comment by 2696120622** [comment]
> Is it possible you are comparing file size with the number of parameters? Although there is a difference. With phi=1 I get 7.6M parameters (with the 80 COCO classes)

With phi=1 I get a parameter file of size 82Mb. Is it possible to reduce the size for inference in mobile?
