### ISSUE TITLE
Modifying anchor boxes

### ISSUE THREAD

**Issue by tanutarou** [xuannianz/EfficientDet#81]
I'm trying to modify the anchor boxes.

I changed only `sizes` and `strides` in `utils/anchors.py`. 
https://github.com/xuannianz/EfficientDet/blob/master/utils/anchors.py#L19-L20

Should I modify other code?

Please let me know if I missed something.
Thanks for all your responses and help.

**Comment by xuannianz** [comment]
Hi @tanutarou , take a look at this line, create a new `AnchorParameters` object with your setting and replace the default. https://github.com/xuannianz/EfficientDet/blob/8c43d7e61e6a64d89570df7d27819e8b2884a851/generators/common.py#L45

**Comment by tanutarou** [comment]
thank you. it works!
