### ISSUE TITLE
csv_generator does not find my files anymore

### ISSUE THREAD

**Issue by SiBensberg** [xuannianz/EfficientDet#82]
The new csv generator does not find my files anymore.

```
File "/home/work/user/modelZoo/EfficientDet_D3_FSoco/generators/csv_.py", line 279, in image_aspect_ratio
    image = Image.open(self.image_path(image_index))
  File "/home/user/.conda/envs/tensorflow/lib/python3.7/site-packages/PIL/Image.py", line 2809, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'fsoco_pictures/Aristurtle images/cam_left0000(1).jpg'
```

I substituted it with the old csv_generator file from before the "Support quadrangle detection" update and it works.

Best regards
Simon

**Comment by xuannianz** [comment]
Hi @SiBensberg , could you help me confirm if it's due to a bug? thanks.

**Comment by SiBensberg** [comment]
I looked in the code and my guess is, the base_dir now gets written empty in line 200. Which leads to a wrong path when calling image.open.
I could not try out yet if this solves my error.

**Comment by SiBensberg** [comment]
Ok, that fixed my error. In csv.py I changed the following lines:
`

        if self.base_dir is None:
            if osp.exists(csv_data_file):
                self.base_dir = ''
            else:
                self.base_dir = osp.dirname(csv_data_file)

`
to:
`

        if self.base_dir is None:
            self.base_dir = osp.dirname(csv_data_file)

`

and it works like before the quadrangle update. Is that intended or are my paths wrong?
