### ISSUE TITLE
Rotated quadrangle annotation

### ISSUE THREAD

**Issue by rose-jinyang** [xuannianz/EfficientDet#83]
Hello
Thanks for supporting the rotated quadrangle detection.
Could you tell me what is the best tool for rotated quadrangle annotation of 2D image?
Thanks

**Comment by ConnorMcShane** [comment]
@rose-jinyang  Hi Rose, I see you are interesting in training with rotated bounding boxes. I am too. Did you manage to find a good annotation tool and do you know what the annotation format should be for this? thanks!
