### ISSUE TITLE
 Error when run inference_fronzen_graph.py

### ISSUE THREAD

**Issue by phucnhs** [xuannianz/EfficientDet#88]
hello. 
I am having problems running the file inference_fronzen_graph.py :
      TypeError: Cannot interpret feed_dict key as Tensor: The name 'input_4:0' refers to a Tensor which does not exist. The operation, 'input_4', does not exist in the graph.
I convert to pb and use model efficientNet-B1
how to solve it
thanks !

**Comment by xuannianz** [comment]
Hi @km23630, could you help with this?

**Comment by km23630** [comment]
> Hi @km23630, could you help with this?

yes I'm checking the source code.

**Comment by km23630** [comment]
> hello.
> I am having problems running the file inference_fronzen_graph.py :
> TypeError: Cannot interpret feed_dict key as Tensor: The name 'input_4:0' refers to a Tensor which does not exist. The operation, 'input_4', does not exist in the graph.
> I convert to pb and use model efficientNet-B1
> how to solve it
> thanks !

```
feed_dict = {"input_1:0": image_batch, "input_4:0": anchors_batch}
boxes_batch, scores_batch, labels_batch = sess.run([output_boxes, output_scores, output_labels], feed_dict)
```

Try this code

**Comment by brarrow** [comment]
> > hello.
> > I am having problems running the file inference_fronzen_graph.py :
> > TypeError: Cannot interpret feed_dict key as Tensor: The name 'input_4:0' refers to a Tensor which does not exist. The operation, 'input_4', does not exist in the graph.
> > I convert to pb and use model efficientNet-B1
> > how to solve it
> > thanks !
> 
> ```
> feed_dict = {"input_1:0": image_batch, "input_4:0": anchors_batch}
> boxes_batch, scores_batch, labels_batch = sess.run([output_boxes, output_scores, output_labels], feed_dict)
> ```
> 
> Try this code

I'm faced with this problem too
This is not helped
Looks like there is no input_4 in Graph

**Comment by greenbarrow** [comment]
@km23630 Can you please help with this problem?

**Comment by brarrow** [comment]
Ok, i just removed 
`"input_4:0": anchors_batch`
And all works now

**Comment by AutumnZ-94** [comment]
> Ok, i just removed
> `"input_4:0": anchors_batch`
> And all works now

so will this effect the accuracy? since i got low scores with this inference code when i remove input_4

**Comment by vaibhavmehrotraml** [comment]
Can this issue be reopened? There has not been any adequate answer
