### ISSUE TITLE
no module named 'utils.compute_overlap'

### ISSUE THREAD

**Issue by hermanius** [xuannianz/EfficientDet#89]
When I try to run inference.py I get

Traceback (most recent call last):
  File "inference.py", line 1, in <module>
    from model import efficientdet
  File "/EfficientDet/model.py", line 17, in <module>
    from utils.anchors import anchors_for_shape
  File "/EfficientDet/utils/anchors.py", line 5, in <module>
    from utils.compute_overlap import compute_overlap
ModuleNotFoundError: No module named 'utils.compute_overlap'

Do I have to change something to make it work?

**Comment by xuannianz** [comment]
Hi @hermanius ,you can pull the `setup.py' and run `python setup.py build_ext --inplace`.

**Comment by hermanius** [comment]
Hi @xuannianz , that solved the issue, thank you very much for the patch.
I now have the following error running inference.py:
(Let me know wether I should open this as a separate issue)

Traceback (most recent call last):
  File "inference.py", line 71, in <module>
    main()
  File "inference.py", line 28, in main
    score_threshold=score_threshold)
  File "/EfficientDet/model.py", line 233, in efficientdet
    features = backbone_cls(input_tensor=image_input, freeze_bn=freeze_bn)
  File "/EfficientDet/utils/__init__.py", line 58, in wrapper
    return func(*args, **kwargs)
  File "/EfficientDet/efficientnet.py", line 471, in EfficientNetB1
    **kwargs)
  File "/EfficientDet/efficientnet.py", line 395, in EfficientNet
    x = BatchNormalization(freeze=freeze_bn, axis=bn_axis, name='stem_bn')(x)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/engine/base_layer.py", line 842, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/impl/api.py", line 237, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

    /EfficientDet/layers.py:22 call  *
        if not training:
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/operators/control_flow.py:893 if_stmt
        basic_symbol_names, composite_symbol_names)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/autograph/operators/control_flow.py:931 tf_if_stmt
        error_checking_orelse)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py:507 new_func
        return func(*args, **kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py:1174 cond
        return cond_v2.cond_v2(pred, true_fn, false_fn, name)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/cond_v2.py:93 cond_v2
        verify_captures(_COND, [true_graph, false_graph])
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/cond_v2.py:768 verify_captures
        b1name=branch_names[i]))

    ValueError: Tensor stem_bn_trainable:0 in true_fn is accessed from false_fn.

I'm using the efficientnet-b4_weights_tf_dim_ordering_tf_kernels_autoaugment.h5 model from 'master' of github.com:Callidior/keras-applications

**Comment by hermanius** [comment]
I just saw the Callidor models are efficientnet backbone models and not efficientdet models, so of course it's not possible to just use them as pretrained models for your repo.

I suppose you don't have good efficientdet pretrained models available that you can share, and that can be used for finetuning (transfer learning)?
