### ISSUE TITLE
For the training and testin speed wondering

### ISSUE THREAD

**Issue by AutumnZ-94** [xuannianz/EfficientDet#91]
Hi Xuannian, 

Thanks for your working on this.

Just wondering, would you say the training speed of the EfficientDet is slow?

I'm using a Tesla P40 with the same parameters as you set in your README, it almost took a hour to train 1 epoch with no more than 20k images.

Have you tried to change the `channels_last` to `channels_first` on GPU training? As discussed in this issue [https://github.com/tensorflow/tpu/issues/389]

Is that something wrong with my setting or just normal speed for this? How about your speed on traing BTW.

Regards,
Autumn

**Comment by xuannianz** [comment]
Yes, it's normal. I did not know `channels_first` was faster. Interesting.

**Comment by AutumnZ-94** [comment]
oh hi, I'm back again.

Thanks for your codes again, and I tested on my data, it prob took 10s on 100 images, and about 4s on CenterNet-ResNet18.

Do you have any reference on inference time either?

BTW, they officially released a new **EfficientNet-Lite** version yesterday in their [repo,](https://github.com/tensorflow/tpu/tree/master/models/official/efficientnet/lite)
