### ISSUE TITLE
about smooth L1 loss

### ISSUE THREAD

**Issue by JIEMIN1995** [xuannianz/EfficientDet#93]
Appreciate your great work! I found the smooth L1 (huber) loss in losses.py is different from the common huber loss format. I don't know the reason of such modifications.

**Comment by xuannianz** [comment]
Hi @JIEMIN1995 , I don't know "common huber loss format", could you attach it? Let me find out what are the differences.

**Comment by JIEMIN1995** [comment]
common format :  
  0.5 * x^2                  if |x| <= d
  d * |x| - 0.5 * d^2     if |x| > d     ,   where d is delta and x is the difference between predictions and labels

yours : 
f(x) = 0.5 * (sigma * x)^2          if |x| < 1 / sigma / sigma
         |x| - 0.5 / sigma / sigma    otherwise

**Comment by xuannianz** [comment]
https://github.com/rbgirshick/py-faster-rcnn/files/764206/SmoothL1Loss.1.pdf
This is the official doc.
