### ISSUE TITLE
Using 6 v100gpus to train the efficentdet of Phi=6 indicates insufficient graphics memory

### ISSUE THREAD

**Issue by liningxiao** [xuannianz/EfficientDet#94]
**I used 6 v100gpus to train efficiendet phi = 6, which still indicated insufficient memory**
I have added the following configuration：
--multi-gpu-force
model=multi_gpu_model(model,gpus=6)
--gpu 0,1,2,3,4,5
What additional configuration is needed?

2020-03-0308:32:44.059062: I tensorflow/ core/ common runtime/bfc_ allocator.cc:929] Stats:
L imit:
32067534848
InUse:
32067527680
MaxInUse:
32067527680
NumAllocs :
27216
MaxAllocSize:
3463708672
2020-03-03 08:32:44. 059537: W tensorflow/ core/ common runtime/bfc_ allocator.cc:424] *****2020-03-03 08:32:44. 059537: W tensorflow/ core/ common runtime/bfc_ allocator.cc:424] *****
***********************************************************************************
2020-03-03 08:32:44. 059576: W tensorflow/core/ framework/op_ kernel. CC:1651] OP_ REQUIRES failed at tra
nspose_ op.Cc:198 : Resource exhausted: 00M when allocating tensor. with shape[1,384,44,44] and type f
loat on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_ 0_ bfc
Traceback (most recent call last) :
File "train.py", line 386，in <module>

**Comment by MathieuHaller** [comment]
Looking through the train.py code, I see this option:
'--num_gpus', help='Number of GPUs to use for parallel processing.', type=int, default=0

Could you try changing this number ?

**Comment by hermanius** [comment]
I did a D4 model training on a Quadro P6000 with a very small dataset with only around 500 images (--freeze-backbone), for 50 epochs, 1000 steps and --batch-size 4.
It trained for more than 1 day, but first tests look encouraging (without any real accuracy testing), Performance is a bit disappointing. Inference time on a Quadro P4000 after warmup is around 5fps.

**Comment by liningxiao** [comment]
> I did a D4 model training on a Quadro P6000 with a very small dataset with only around 500 images (--freeze-backbone), for 50 epochs, 1000 steps and --batch-size 4.
> It trained for more than 1 day, but first tests look encouraging (without any real accuracy testing), Performance is a bit disappointing. Inference time on a Quadro P4000 after warmup is around 5fps.

The test speed on the paper is performed on the TPU. I also use the model trained by D4. The test speed on the 1080ti is 3-4 times the time in the paper.

**Comment by liningxiao** [comment]
> Looking through the train.py code, I see this option:
> '--num_gpus', help='Number of GPUs to use for parallel processing.', type=int, default=0
> 
> Could you try configuring this option as well ?

I tried this setting and it didn't work

**Comment by hermanius** [comment]
When running the D4 model on an Nvidia Jetson Xavier (Tensorflow 2.1 in a docker container) and setting a gpu memory limit to 512MB I get a performance around 2.5fps, which is not bad.
I have tried to convert it to Tensorflow-TRT on the Xavier but the conversion failed. (I'm not saying there is something wrong with the repo, just that I was not able to convert it yet).
On a MobileV2 model for classification converting with Tensorflow-TRT gave me a 100X performance improvement...

**Comment by xuannianz** [comment]
Hi @liningxiao , pull the latest code and try `--gpu '1,2,3'` for example.

**Comment by liningxiao** [comment]
> Hi @liningxiao , pull the latest code and try `--gpu 1,2,3` for example.

The parameter gpus is the number of GPUs or a list of GPU IDs?

**Comment by xuannianz** [comment]
@liningxiao , a list of gpu ids.
