### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.compute_overlap'

### ISSUE THREAD

**Issue by wxyhv** [xuannianz/EfficientDet#95]
请问python3.7版本下如何编译生成compute_overlap.cpython-36m-x86_64-linux-gnu.so ??

**Comment by wxyhv** [comment]
How to get the file 'compute_overlap.cpython-36m-x86_64-linux-gnu.so' in python3.7 ?

**Comment by wxyhv** [comment]
I have committed a compute_overlap.py, which was rewriten through compute_overlap.pyx. This document is work.

**Comment by xuannianz** [comment]
Hi @wxyhv, check this. #89
