### ISSUE TITLE
How can I accelerate the speed of preprocess images?

### ISSUE THREAD

**Issue by xinlnix** [xuannianz/EfficientDet#99]
pre:0.02557992935180664        #preprocess_inp_det 
pro:0.022922039031982422      #preprocess_inp_det 
detect:0.024942874908447266 #detetct use efficientdet on gpu
As you can see,preprocess and process image speed twice time more than object detect.How can I accelerate the rate? Here is the code:

def preprocess_inp_det(path):#preprocess_inp_det
    inp_image = cv2.imread(path)
    src_image = inp_image.copy()
    inp_image = inp_image[:, :, ::-1]#to rgb
    h, w = inp_image.shape[:2]
    return src_image, inp_image, h, w

def processing_inp_det(image, image_size):
    image_height, image_width = image.shape[:2]
    if image_height > image_width:
        scale = image_size / image_height
        resized_height = image_size
        resized_width = int(image_width * scale)
    else:
        scale = image_size / image_width
        resized_height = int(image_height * scale)
        resized_width = image_size
    
    image = cv2.resize(image, (resized_width, resized_height))
    new_image = np.ones((image_size, image_size, 3), dtype=np.float32) * 128.
    offset_h = (image_size - resized_height) // 2
    offset_w = (image_size - resized_width) // 2
    new_image[offset_h:offset_h + resized_height, offset_w:offset_w + resized_width] = image.astype(np.float32)
    new_image /= 255.
    
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]
    
    for i in range(3):
        new_image[..., i] -= mean[i]
        new_image[..., i] /= std[i]
    
    return new_image, scale, offset_h, offset_w

**Comment by km23630** [comment]
I tried a lot to speed up the preprocess but didn't show any significant speed difference.
:(

**Comment by bhack** [comment]
Have you tried to profile with https://github.com/benfred/py-spy?

**Comment by km23630** [comment]
> Have you tried to profile with https://github.com/benfred/py-spy?

i tried python package line_profiler

**Comment by bhack** [comment]
Ok and what Is your profile result on the single preprocessing lines?

**Comment by km23630** [comment]
In my case, 
preprocessing time was 0.00620325 per single image
It take 30% of the whole process time

**Comment by bhack** [comment]
No I meant more: cv2.resize and for loop Intra timing.

**Comment by km23630** [comment]
![image](https://user-images.githubusercontent.com/30399899/76399672-5e974a80-63c2-11ea-9bbc-db283da1917f.png)

refer this profile result

**Comment by bhack** [comment]
The resize it Is quite dominant can you work with ROI in your case?
Also for the loop do you need per-channel normalizzation or you can use https://www.tensorflow.org/api_docs/python/tf/image/per_image_standardization?

**Comment by bhack** [comment]
Check also https://stackoverflow.com/questions/54155481/tensorflow-per-image-standardization-vs-mean-standardization-across-full-dataset
